var INFO = {
  "BREAK (DESTROY OR GET DESTROYED)": "infomap_18_BREAK (CLEAVE)",
  "MORE": "infomap_20_ENOUGH",
  "EMERGE (APPEAR)": "infomap_91_SEEM",
  "GO UP (ASCEND)": "infomap_51_RISE (MOVE UPWARDS)",
  "CAN": "infomap_211_TINPLATE",
  "PEEL": "infomap_245_PEEL",
  "DIE": "infomap_68_DIE",
  "DAMAGE (INJURY)": "infomap_105_BAD",
  "COPPER": "infomap_133_KNIFE",
  "STATE (POLITICS)": "infomap_9_COUNTRY",
  "DAMAGE": "infomap_18_BREAK (CLEAVE)",
  "JOG (SOMETHING)": "infomap_63_SHAKE",
  "GRAPE": "infomap_25_THREAD",
  "MONEY": "infomap_176_COIN",
  "MOVE (ONESELF)": "infomap_253_BUDGE (ONESELF)",
  "BALL": "infomap_83_CIRCLE",
  "STAR": "infomap_104_FISH",
  "RAIN (PRECIPITATION)": "infomap_31_WATER",
  "ARM": "infomap_29_ARM",
  "PROUD": "infomap_61_ASK (REQUEST)",
  "CROOKED": "infomap_59_TWIST",
  "BOIL (OF SKIN)": "infomap_90_WOUND",
  "SCRAPE": "infomap_94_SWEEP",
  "HAWK": "infomap_148_VULTURE",
  "SPOIL (SOMEBODY OR SOMETHING)": "infomap_18_BREAK (CLEAVE)",
  "TINKLE": "infomap_43_CHIME (ACTION)",
  "LIE DOWN": "infomap_134_SLEEP",
  "YES": "infomap_6_CORRECT (RIGHT)",
  "DIVIDE": "infomap_180_SEPARATE",
  "SWIM": "infomap_81_SWIM",
  "NEVER": "infomap_132_OFTEN",
  "PARENTS": "infomap_30_RELATIVES",
  "ROPE": "infomap_25_THREAD",
  "BODY LOUSE": "infomap_294_HEAD LOUSE",
  "LAW": "infomap_212_CUSTOM",
  "WOMB": "infomap_106_INTESTINES",
  "CEASE": "infomap_86_STAND",
  "CHURCH": "infomap_216_TEMPLE",
  "COLOR": "infomap_117_DYE",
  "PROMISE": "infomap_224_SWEAR",
  "FEATHER": "infomap_4_FUR",
  "WOOD": "infomap_2_WOOD",
  "UNRIPE": "infomap_97_GREEN",
  "CARPENTER": "infomap_272_MASON",
  "FINGERNAIL": "infomap_136_FINGERNAIL",
  "OAT": "infomap_7_GRAIN",
  "PUT": "infomap_214_SEAT (SOMEBODY)",
  "FATHER": "infomap_152_FATHER'S BROTHER",
  "CROWD": "infomap_20_ENOUGH",
  "EXPLAIN": "infomap_1_SPEAK",
  "NEEDLE TREE": "infomap_118_NEEDLE (FOR SEWING)",
  "FOREHEAD": "infomap_231_FACE",
  "COLD (CHILL)": "infomap_124_FROST",
  "MAD": "infomap_144_MUTE",
  "STORE": "infomap_268_STORE",
  "LUNCH": "infomap_53_DINNER (SUPPER)",
  "VILLAGE": "infomap_302_VILLAGE",
  "LIGHTNING": "infomap_155_THUNDER",
  "YAM": "infomap_204_POTATO",
  "STEP (VERB)": "infomap_54_WALK",
  "CLEAN": "infomap_12_LIGHT (RADIATION)",
  "THREATEN": "infomap_166_SCOLD",
  "END (OF SPACE)": "infomap_174_LAST (FINAL)",
  "IRON": "infomap_133_KNIFE",
  "RETURN HOME": "infomap_46_COME BACK",
  "HE-GOAT": "infomap_64_SHEEP",
  "RING (MAKE SOUND)": "infomap_43_CHIME (ACTION)",
  "LOCK": "infomap_147_LATCH",
  "HEAT": "infomap_151_HEAT",
  "THINK (BELIEVE)": "infomap_71_THINK (REFLECT)",
  "GO DOWN (DESCEND)": "infomap_312_GO DOWN (DESCEND)",
  "FATHER-IN-LAW (OF WOMAN)": "infomap_10_SON-IN-LAW (OF MAN)",
  "BRAIN": "infomap_3_MIND",
  "SPINE": "infomap_223_BACK",
  "LIFT": "infomap_109_PICK UP",
  "LIVER": "infomap_3_MIND",
  "DWELL (LIVE, RESIDE)": "infomap_16_REMAIN",
  "TENT": "infomap_56_HOUSE",
  "MEETING HOUSE": "infomap_216_TEMPLE",
  "BLOOD": "infomap_50_YELLOW",
  "LONG": "infomap_13_HIGH",
  "PLOUGH": "infomap_137_CULTIVATE",
  "ACQUIT": "infomap_41_UNTIE",
  "CRIME": "infomap_14_FAULT",
  "FIR": "infomap_297_FIR",
  "SPRING (OF WATER)": "infomap_266_WELL",
  "KNEEL": "infomap_29_ARM",
  "AND": "infomap_20_ENOUGH",
  "TOWEL": "infomap_24_CLOTH",
  "MOSQUITO": "infomap_220_MOSQUITO",
  "FORMER": "infomap_33_OLD",
  "CARRY UNDER ARM": "infomap_66_CARRY",
  "STREAM (FLOW CONTINUOUSLY)": "infomap_70_RUN",
  "IT": "infomap_22_THAT",
  "DAUGHTER-IN-LAW (OF MAN)": "infomap_10_SON-IN-LAW (OF MAN)",
  "FIGHT": "infomap_178_QUARREL",
  "DECREASE": "infomap_45_SINK (DESCEND)",
  "ALONE": "infomap_210_ONLY",
  "ROW": "infomap_188_ROW",
  "DEFEAT": "infomap_306_DEFEAT",
  "WEDDING": "infomap_233_MARRY",
  "HURRY": "infomap_159_DASH (OF VEHICLE)",
  "GRANDCHILD": "infomap_73_GRANDSON",
  "STALLION": "infomap_79_HORSE",
  "TURTLE": "infomap_271_TORTOISE",
  "SPLEEN": "infomap_3_MIND",
  "MOVE (AFFECT EMOTIONALLY)": "infomap_5_UNDERSTAND",
  "PLAIT OR BRAID OR WEAVE": "infomap_72_WEAVE",
  "SOUTH": "infomap_318_NORTH",
  "SPIT": "infomap_191_DRIBBLE",
  "STRANGER": "infomap_32_KING",
  "TELL": "infomap_1_SPEAK",
  "PLANT (VEGETATION)": "infomap_2_WOOD",
  "FORKED BRANCH": "infomap_67_PITCHFORK",
  "CLAW": "infomap_136_FINGERNAIL",
  "ENVY": "infomap_240_HATE",
  "REMEMBER": "infomap_71_THINK (REFLECT)",
  "TASTE (SOMETHING)": "infomap_23_COUNT",
  "DISEASE": "infomap_99_SICK",
  "BUDGE (ONESELF)": "infomap_253_BUDGE (ONESELF)",
  "STINKING": "infomap_55_STINKING",
  "SALTY": "infomap_76_SALTY",
  "BIRD": "infomap_103_FOWL",
  "CATCH": "infomap_21_GET",
  "DIE (FROM ACCIDENT)": "infomap_68_DIE",
  "BOY": "infomap_11_BOY",
  "SURPRISED": "infomap_19_GRIEF",
  "DINNER (SUPPER)": "infomap_53_DINNER (SUPPER)",
  "RUN": "infomap_70_RUN",
  "LAMB": "infomap_64_SHEEP",
  "PAPER": "infomap_140_LETTER",
  "LATE": "infomap_120_BE LATE",
  "JUMP": "infomap_230_JUMP",
  "TREE": "infomap_2_WOOD",
  "KISS": "infomap_34_DRINK",
  "SMELL (PERCEIVE)": "infomap_55_STINKING",
  "RAFT": "infomap_80_CANOE",
  "CIGARETTE": "infomap_300_CIGARETTE",
  "REGRET": "infomap_19_GRIEF",
  "NEST": "infomap_48_BLANKET",
  "WING": "infomap_4_FUR",
  "GARDEN-HOUSE": "infomap_56_HOUSE",
  "HUSBAND": "infomap_96_MALE (OF PERSON)",
  "SISTER": "infomap_15_YOUNGER BROTHER",
  "BERRY": "infomap_7_GRAIN",
  "MESSAGE": "infomap_153_STORY",
  "CALM": "infomap_142_QUIET",
  "THICK": "infomap_125_THICK",
  "STONE": "infomap_39_MOUNTAIN",
  "DRIP (FALL IN GLOBULES)": "infomap_190_FALL",
  "PREPARE": "infomap_47_COOK (SOMETHING)",
  "SHRIEK": "infomap_28_SHOUT",
  "VEIN": "infomap_167_TENDON",
  "PAY": "infomap_23_COUNT",
  "DEAD": "infomap_68_DIE",
  "FEEL (TACTUALLY)": "infomap_5_UNDERSTAND",
  "SHALLOW": "infomap_36_LOW",
  "CHEAP": "infomap_215_EASY",
  "IDEA": "infomap_3_MIND",
  "ONE": "infomap_210_ONLY",
  "CHILD (DESCENDANT)": "infomap_11_BOY",
  "SUN": "infomap_35_TIME",
  "LIVESTOCK": "infomap_57_CATTLE",
  "TWO": "infomap_185_PAIR",
  "MEAD": "infomap_101_WINE",
  "TIE UP (TETHER)": "infomap_82_TIE",
  "WRONG": "infomap_14_FAULT",
  "NOW": "infomap_38_IMMEDIATELY",
  "PIG": "infomap_195_SOW (FEMALE PIG)",
  "GHOST": "infomap_3_MIND",
  "BLUNT": "infomap_327_BLUNT",
  "BOIL (OF LIQUID)": "infomap_47_COOK (SOMETHING)",
  "FLESH OR MEAT": "infomap_104_FISH",
  "SEASON": "infomap_35_TIME",
  "BROKEN": "infomap_18_BREAK (CLEAVE)",
  "ARMOUR": "infomap_274_ARMOUR",
  "TRAP (CATCH)": "infomap_21_GET",
  "SUCCEED": "infomap_128_BECOME",
  "UDDER": "infomap_102_BREAST",
  "SING": "infomap_92_SING",
  "LAGOON": "infomap_157_LAGOON",
  "SEAT (SOMEBODY)": "infomap_214_SEAT (SOMEBODY)",
  "AFTER": "infomap_244_AFTER",
  "TOWER": "infomap_93_FENCE",
  "MEDICINE": "infomap_161_MEDICINE",
  "TENDON": "infomap_167_TENDON",
  "MOON": "infomap_251_MOON",
  "BRING": "infomap_66_CARRY",
  "STRONG": "infomap_42_HARD",
  "LONG HAIR": "infomap_323_HAIR (HEAD)",
  "BRACKISH": "infomap_76_SALTY",
  "WEAVE": "infomap_72_WEAVE",
  "WHERE": "infomap_65_WHAT",
  "LANGUAGE": "infomap_1_SPEAK",
  "HUNGER": "infomap_149_HUNGER",
  "MOTOR": "infomap_115_CAR",
  "CURE": "infomap_26_PRESERVE",
  "PILE UP": "infomap_109_PICK UP",
  "OLDER SIBLING": "infomap_15_YOUNGER BROTHER",
  "LAST (ENDURE)": "infomap_120_BE LATE",
  "HOARFROST": "infomap_124_FROST",
  "REMAINS": "infomap_16_REMAIN",
  "WALKING STICK": "infomap_2_WOOD",
  "BOARD": "infomap_135_BOARD",
  "ITEM": "infomap_225_ITEM",
  "SHOULDERBLADE": "infomap_237_SHOULDER",
  "ALL": "infomap_20_ENOUGH",
  "SHADE": "infomap_3_MIND",
  "HOLD": "infomap_21_GET",
  "STOCKING": "infomap_200_SHOE",
  "HUT": "infomap_56_HOUSE",
  "TONE (MUSIC)": "infomap_1_SPEAK",
  "PERSON": "infomap_30_RELATIVES",
  "TWINKLE": "infomap_12_LIGHT (RADIATION)",
  "FRY": "infomap_47_COOK (SOMETHING)",
  "ROTTEN": "infomap_55_STINKING",
  "REFUSE": "infomap_138_FORBID",
  "HIDE (CONCEAL)": "infomap_169_HIDE (CONCEAL)",
  "LAKE": "infomap_157_LAGOON",
  "BE BORN": "infomap_162_BEGET",
  "OLD WOMAN": "infomap_33_OLD",
  "PADLOCK": "infomap_147_LATCH",
  "CONVICT": "infomap_119_ADJUDICATE",
  "CHEW": "infomap_34_DRINK",
  "BORROW": "infomap_88_GIVE",
  "WITHOUT": "infomap_69_NOT",
  "COUNT (QUANTITY)": "infomap_264_COUNT (QUANTITY)",
  "DOOR": "infomap_239_DOOR",
  "FOOT": "infomap_8_LEG",
  "THIGH": "infomap_8_LEG",
  "GUESS": "infomap_71_THINK (REFLECT)",
  "NOTHING": "infomap_69_NOT",
  "HIRE": "infomap_88_GIVE",
  "POINTED": "infomap_249_POINTED",
  "CONCEIVE": "infomap_162_BEGET",
  "TIE": "infomap_82_TIE",
  "RUDDER": "infomap_188_ROW",
  "MAGICIAN": "infomap_197_MAGICIAN",
  "HERD (SOMETHING)": "infomap_26_PRESERVE",
  "URINE": "infomap_31_WATER",
  "MOVE": "infomap_235_MIX",
  "HEIGHT": "infomap_39_MOUNTAIN",
  "MUTE": "infomap_144_MUTE",
  "WIDOW": "infomap_280_WIDOWER",
  "PITCHFORK": "infomap_67_PITCHFORK",
  "UNCLE": "infomap_152_FATHER'S BROTHER",
  "CONVEY (A MESSAGE)": "infomap_1_SPEAK",
  "PEACE": "infomap_142_QUIET",
  "SUGAR": "infomap_170_SUGAR",
  "DRINK": "infomap_34_DRINK",
  "BAG": "infomap_202_BAG",
  "MOLD": "infomap_238_CAST",
  "WORSHIP": "infomap_61_ASK (REQUEST)",
  "LIKE": "infomap_113_WANT",
  "TROUGH": "infomap_80_CANOE",
  "PICTURE": "infomap_208_IDOL",
  "EAT": "infomap_34_DRINK",
  "VULVA": "infomap_260_VULVA",
  "WIDOWER": "infomap_280_WIDOWER",
  "SHOVEL": "infomap_182_SPADE",
  "OTHER": "infomap_164_SECOND",
  "NAVEL": "infomap_78_PART",
  "NAME": "infomap_28_SHOUT",
  "SHOOT": "infomap_228_THROW",
  "RAZOR": "infomap_133_KNIFE",
  "SHOP": "infomap_305_SHOP",
  "MIDDAY": "infomap_53_DINNER (SUPPER)",
  "FLAT": "infomap_49_SMOOTH",
  "WOUND": "infomap_90_WOUND",
  "SIN": "infomap_14_FAULT",
  "DIFFICULT": "infomap_42_HARD",
  "FAST": "infomap_38_IMMEDIATELY",
  "COW": "infomap_57_CATTLE",
  "EVENING": "infomap_27_DARKNESS",
  "CENTIPEDE": "infomap_293_CENTIPEDE",
  "TOP": "infomap_13_HIGH",
  "WRIST": "infomap_29_ARM",
  "RIDE": "infomap_51_RISE (MOVE UPWARDS)",
  "TONGUE": "infomap_1_SPEAK",
  "HOUSE": "infomap_56_HOUSE",
  "AT": "infomap_179_IN",
  "GOOD": "infomap_6_CORRECT (RIGHT)",
  "DREAM (SOMETHING)": "infomap_134_SLEEP",
  "TRY": "infomap_23_COUNT",
  "HAIR": "infomap_4_FUR",
  "MANY": "infomap_20_ENOUGH",
  "PURSUE": "infomap_259_PURSUE",
  "BOAT": "infomap_80_CANOE",
  "LINE": "infomap_25_THREAD",
  "CITIZEN": "infomap_30_RELATIVES",
  "SET (HEAVENLY BODIES)": "infomap_45_SINK (DESCEND)",
  "BLOW (OF WIND)": "infomap_127_BLOW (OF WIND)",
  "BEND": "infomap_59_TWIST",
  "DONATE": "infomap_88_GIVE",
  "CLOUD": "infomap_121_FOG",
  "GROW": "infomap_51_RISE (MOVE UPWARDS)",
  "SWALLOW": "infomap_34_DRINK",
  "LOSE": "infomap_255_DISAPPEAR",
  "HAPPINESS": "infomap_292_HAPPINESS",
  "AIR": "infomap_87_BREATHE",
  "SPIRIT": "infomap_3_MIND",
  "BUSH": "infomap_39_MOUNTAIN",
  "PERMIT": "infomap_41_UNTIE",
  "YOUNG WOMAN": "infomap_11_BOY",
  "KEY": "infomap_147_LATCH",
  "PEPPER": "infomap_282_CHILI PEPPER",
  "NEWS": "infomap_153_STORY",
  "CLIMB": "infomap_51_RISE (MOVE UPWARDS)",
  "SAUSAGE": "infomap_106_INTESTINES",
  "FORGIVE": "infomap_41_UNTIE",
  "WIND": "infomap_87_BREATHE",
  "PALM OF HAND": "infomap_29_ARM",
  "EWE": "infomap_64_SHEEP",
  "WELL": "infomap_266_WELL",
  "HEAVY": "infomap_42_HARD",
  "THIN": "infomap_111_NARROW",
  "HANG": "infomap_321_HANG",
  "LAST (FINAL)": "infomap_174_LAST (FINAL)",
  "BREAST": "infomap_102_BREAST",
  "MORTAR CRUSHER": "infomap_226_MORTAR CRUSHER",
  "HAMMER": "infomap_84_STRIKE OR BEAT",
  "GRAIN": "infomap_7_GRAIN",
  "SEE": "infomap_74_SEE",
  "WEALTH": "infomap_326_WEALTH",
  "BEAN": "infomap_275_KIDNEY",
  "TURN AROUND": "infomap_46_COME BACK",
  "AUTUMN": "infomap_107_SUMMER",
  "MAN": "infomap_96_MALE (OF PERSON)",
  "PLATE": "infomap_98_BOWL",
  "DAY AFTER TOMORROW": "infomap_288_DAY BEFORE YESTERDAY",
  "BOUNDARY": "infomap_17_EDGE",
  "BRICK": "infomap_304_BRICK",
  "CHEEK": "infomap_112_CHIN",
  "AFTERNOON": "infomap_120_BE LATE",
  "LEAD (GUIDE)": "infomap_66_CARRY",
  "CARRY ON HEAD": "infomap_66_CARRY",
  "FOOTPRINT": "infomap_100_PATH",
  "WE (EXCLUSIVE)": "infomap_114_WE (INCLUSIVE)",
  "GAME": "infomap_92_SING",
  "OBSCURE": "infomap_27_DARKNESS",
  "TIDE": "infomap_206_TIDE",
  "RIPE": "infomap_50_YELLOW",
  "CLOAK": "infomap_48_BLANKET",
  "SHOE": "infomap_200_SHOE",
  "SERVANT": "infomap_123_PRISON",
  "MARRY": "infomap_233_MARRY",
  "SWEAR": "infomap_224_SWEAR",
  "WAIST": "infomap_8_LEG",
  "COUNTRY": "infomap_9_COUNTRY",
  "CLOTH": "infomap_24_CLOTH",
  "HORSE": "infomap_79_HORSE",
  "FACE": "infomap_231_FACE",
  "CONVERSATION": "infomap_1_SPEAK",
  "CUT": "infomap_60_CUT",
  "NOSTRIL": "infomap_131_COMMON COLD (DISEASE)",
  "THITHER (THERE TO)": "infomap_172_THERE",
  "THIRD": "infomap_287_THIRD",
  "OBEY": "infomap_5_UNDERSTAND",
  "TEACHER": "infomap_316_PUPIL (STUDENT)",
  "LAY (VERB)": "infomap_214_SEAT (SOMEBODY)",
  "PETROLEUM": "infomap_75_FAT (ORGANIC SUBSTANCE)",
  "FLOWER": "infomap_50_YELLOW",
  "MAKE NOISE": "infomap_43_CHIME (ACTION)",
  "NEEDLE (FOR SEWING)": "infomap_118_NEEDLE (FOR SEWING)",
  "TWINS": "infomap_185_PAIR",
  "AXLE": "infomap_278_AXLE",
  "DISAPPEAR": "infomap_255_DISAPPEAR",
  "DISTANCE": "infomap_145_GAP (DISTANCE)",
  "CROCODILE": "infomap_286_LIZARD",
  "CLEAR": "infomap_12_LIGHT (RADIATION)",
  "NOTICE (SOMETHING)": "infomap_5_UNDERSTAND",
  "MAST": "infomap_2_WOOD",
  "MIND": "infomap_3_MIND",
  "GENTLE": "infomap_49_SMOOTH",
  "HOST": "infomap_32_KING",
  "HOPE": "infomap_113_WANT",
  "HELP": "infomap_26_PRESERVE",
  "STREAM": "infomap_31_WATER",
  "PIECE": "infomap_78_PART",
  "BAKE": "infomap_47_COOK (SOMETHING)",
  "LOWER ARM": "infomap_250_LOWER ARM",
  "WHY": "infomap_65_WHAT",
  "ORDER": "infomap_209_SEND",
  "POWERFUL": "infomap_42_HARD",
  "FEMALE (OF PERSON)": "infomap_58_WIFE",
  "AXE": "infomap_193_AXE",
  "SEW": "infomap_72_WEAVE",
  "DIG": "infomap_156_HOLLOW OUT",
  "EDGE": "infomap_17_EDGE",
  "TOUCH": "infomap_5_UNDERSTAND",
  "FELT": "infomap_4_FUR",
  "OAK": "infomap_279_OAK",
  "MURDER": "infomap_177_EXTINGUISH",
  "BATHE": "infomap_81_SWIM",
  "MELT": "infomap_273_THAW (DEW)",
  "FINGER": "infomap_254_TOE",
  "ANNOUNCE": "infomap_1_SPEAK",
  "SCOLD": "infomap_166_SCOLD",
  "BEEHIVE": "infomap_110_HONEY",
  "CLEAN (SOMETHING)": "infomap_94_SWEEP",
  "CARRY": "infomap_66_CARRY",
  "SUCK": "infomap_34_DRINK",
  "BABY": "infomap_11_BOY",
  "PLACE (POSITION)": "infomap_9_COUNTRY",
  "FORK": "infomap_67_PITCHFORK",
  "INJURE": "infomap_18_BREAK (CLEAVE)",
  "FISH TRAP": "infomap_85_NETBAG",
  "CHEST": "infomap_102_BREAST",
  "DEATH": "infomap_68_DIE",
  "WALK": "infomap_54_WALK",
  "SPLIT": "infomap_60_CUT",
  "TALK": "infomap_1_SPEAK",
  "GRANDFATHER": "infomap_33_OLD",
  "TRADE OR BARTER": "infomap_89_SELL",
  "POISON": "infomap_161_MEDICINE",
  "THROW": "infomap_228_THROW",
  "FLOCK (OF ANIMALS)": "infomap_270_SWARM (OF BIRDS)",
  "DEW": "infomap_213_SNOW",
  "RIPEN": "infomap_47_COOK (SOMETHING)",
  "TODAY": "infomap_38_IMMEDIATELY",
  "RIB": "infomap_8_LEG",
  "OVEN": "infomap_154_FIREPLACE",
  "WEIGH": "infomap_23_COUNT",
  "MUD": "infomap_139_SWAMP",
  "WORK (ACTIVITY)": "infomap_52_BUILD",
  "DESCENDANTS": "infomap_11_BOY",
  "FINE OR THIN": "infomap_111_NARROW",
  "FIG": "infomap_276_BANYAN",
  "BANYAN": "infomap_276_BANYAN",
  "TIME": "infomap_35_TIME",
  "WINTER": "infomap_124_FROST",
  "LUNG": "infomap_171_DUST",
  "SEPARATE": "infomap_180_SEPARATE",
  "PRAY": "infomap_61_ASK (REQUEST)",
  "SHOW": "infomap_91_SEEM",
  "EYE": "infomap_231_FACE",
  "RICH": "infomap_326_WEALTH",
  "SLAVE": "infomap_123_PRISON",
  "THIEF": "infomap_169_HIDE (CONCEAL)",
  "BOOT": "infomap_200_SHOE",
  "FLY (MOVE THROUGH AIR)": "infomap_230_JUMP",
  "UP": "infomap_13_HIGH",
  "ROOSTER": "infomap_103_FOWL",
  "STEPFATHER": "infomap_10_SON-IN-LAW (OF MAN)",
  "SLIP": "infomap_49_SMOOTH",
  "LAZY": "infomap_49_SMOOTH",
  "LET GO OR SET FREE": "infomap_41_UNTIE",
  "SAND": "infomap_9_COUNTRY",
  "CANDLE": "infomap_129_CANDLE",
  "EMPTY": "infomap_69_NOT",
  "ROAR (OF SEA)": "infomap_159_DASH (OF VEHICLE)",
  "PISS": "infomap_295_SHIT (DEFECATE)",
  "BEHIND": "infomap_244_AFTER",
  "GRIND": "infomap_77_SQUEEZE",
  "ADOBE": "infomap_304_BRICK",
  "DARK": "infomap_27_DARKNESS",
  "RAINBOW": "infomap_108_BOW",
  "DANGER": "infomap_19_GRIEF",
  "TOE": "infomap_254_TOE",
  "SHELF": "infomap_135_BOARD",
  "WHITE": "infomap_12_LIGHT (RADIATION)",
  "BETWEEN": "infomap_145_GAP (DISTANCE)",
  "MASTER": "infomap_32_KING",
  "FISH": "infomap_104_FISH",
  "FISH POISON": "infomap_161_MEDICINE",
  "RIGHT": "infomap_6_CORRECT (RIGHT)",
  "SHEEP": "infomap_64_SHEEP",
  "INSTANTLY": "infomap_38_IMMEDIATELY",
  "AUNT": "infomap_160_MOTHER'S SISTER",
  "LIBERATE": "infomap_41_UNTIE",
  "CALF OF LEG": "infomap_8_LEG",
  "COIN": "infomap_176_COIN",
  "WHAT": "infomap_65_WHAT",
  "CLAN": "infomap_30_RELATIVES",
  "MULE": "infomap_79_HORSE",
  "POUCH": "infomap_202_BAG",
  "ENTER": "infomap_45_SINK (DESCEND)",
  "THERE": "infomap_172_THERE",
  "SHIN": "infomap_8_LEG",
  "RIDGEPOLE": "infomap_187_RAFTER",
  "NIGHT": "infomap_27_DARKNESS",
  "MOW": "infomap_60_CUT",
  "FATHER'S BROTHER": "infomap_152_FATHER'S BROTHER",
  "CHILD-IN-LAW": "infomap_10_SON-IN-LAW (OF MAN)",
  "SOUR": "infomap_76_SALTY",
  "ELEVATION": "infomap_39_MOUNTAIN",
  "RAISE (A CHILD)": "infomap_320_FEED",
  "SACK": "infomap_202_BAG",
  "THIN (SLIM)": "infomap_111_NARROW",
  "REPAIR": "infomap_291_IMPROVE (SOMETHING)",
  "DRIVE": "infomap_54_WALK",
  "IF": "infomap_165_BECAUSE",
  "SOW SEEDS": "infomap_137_CULTIVATE",
  "OUTRIGGER": "infomap_80_CANOE",
  "MOLAR TOOTH": "infomap_44_BEAK",
  "SIT": "infomap_16_REMAIN",
  "HE OR SHE OR IT": "infomap_22_THAT",
  "BOAST": "infomap_61_ASK (REQUEST)",
  "HOW MUCH": "infomap_248_HOW MANY",
  "COUNT": "infomap_23_COUNT",
  "WEIGHT": "infomap_311_LOAD",
  "PONCHO": "infomap_48_BLANKET",
  "FLOAT": "infomap_81_SWIM",
  "SON-IN-LAW (OF MAN)": "infomap_10_SON-IN-LAW (OF MAN)",
  "THAT": "infomap_22_THAT",
  "GLASS": "infomap_141_MIRROR",
  "MACHINE": "infomap_115_CAR",
  "GO OUT": "infomap_54_WALK",
  "FIN": "infomap_4_FUR",
  "HONEY": "infomap_110_HONEY",
  "KNEE": "infomap_29_ARM",
  "ABOVE": "infomap_13_HIGH",
  "MAKE": "infomap_52_BUILD",
  "WHO": "infomap_65_WHAT",
  "FAT (ORGANIC SUBSTANCE)": "infomap_75_FAT (ORGANIC SUBSTANCE)",
  "UPPER BACK": "infomap_223_BACK",
  "FISHHOOK": "infomap_184_HOOK",
  "STROKE (OF PEN)": "infomap_25_THREAD",
  "ELBOW": "infomap_29_ARM",
  "GRASP": "infomap_21_GET",
  "MATCH": "infomap_130_FIRE",
  "OWE": "infomap_227_DEBT",
  "SPRING OR WELL": "infomap_40_HOLE",
  "DIRT": "infomap_27_DARKNESS",
  "RED": "infomap_50_YELLOW",
  "DEBT": "infomap_227_DEBT",
  "FIREPLACE": "infomap_154_FIREPLACE",
  "OUTSIDE": "infomap_93_FENCE",
  "KETTLE": "infomap_163_POT",
  "DEEP": "infomap_13_HIGH",
  "NEW": "infomap_221_FRESH",
  "WATER": "infomap_31_WATER",
  "FAIRY TALE": "infomap_153_STORY",
  "HERE": "infomap_172_THERE",
  "HILL": "infomap_39_MOUNTAIN",
  "PRESS": "infomap_77_SQUEEZE",
  "WAGES": "infomap_126_EXPENSIVE",
  "HIP": "infomap_8_LEG",
  "POUND": "infomap_84_STRIKE OR BEAT",
  "DRAG": "infomap_168_STRETCH",
  "PRODUCE": "infomap_52_BUILD",
  "COMB (VERB)": "infomap_205_COMB",
  "DEFEND": "infomap_26_PRESERVE",
  "LEGENDARY CREATURE": "infomap_3_MIND",
  "HANG UP": "infomap_321_HANG",
  "LEAVE": "infomap_54_WALK",
  "LAIR": "infomap_40_HOLE",
  "RISE (MOVE UPWARDS)": "infomap_51_RISE (MOVE UPWARDS)",
  "RIVER": "infomap_31_WATER",
  "LETTER": "infomap_140_LETTER",
  "WIDE": "infomap_125_THICK",
  "PERJURY": "infomap_189_DECEIT",
  "THUNDER": "infomap_155_THUNDER",
  "TINPLATE": "infomap_211_TINPLATE",
  "DOWN": "infomap_36_LOW",
  "DAY (24 HOURS)": "infomap_35_TIME",
  "HEAR": "infomap_5_UNDERSTAND",
  "SHEARS": "infomap_269_CHISEL",
  "SHARE": "infomap_180_SEPARATE",
  "SPEECH": "infomap_1_SPEAK",
  "FISHING LINE": "infomap_25_THREAD",
  "UNDERSTAND": "infomap_5_UNDERSTAND",
  "LOW": "infomap_36_LOW",
  "SEVERE": "infomap_105_BAD",
  "OIL (ORGANIC SUBSTANCE)": "infomap_75_FAT (ORGANIC SUBSTANCE)",
  "STATUE": "infomap_208_IDOL",
  "SHUT": "infomap_252_SHUT",
  "SPACE (AVAILABLE)": "infomap_145_GAP (DISTANCE)",
  "FREEZE": "infomap_63_SHAKE",
  "HIT": "infomap_43_CHIME (ACTION)",
  "SON-IN-LAW (OF WOMAN)": "infomap_10_SON-IN-LAW (OF MAN)",
  "BROOM": "infomap_67_PITCHFORK",
  "FEMALE (OF ANIMAL)": "infomap_58_WIFE",
  "MIRROR": "infomap_141_MIRROR",
  "TERMITE": "infomap_285_TERMITE",
  "BACKWARD": "infomap_257_BACKWARD",
  "SHIVER": "infomap_63_SHAKE",
  "COLLAR": "infomap_146_THROAT",
  "SWEET POTATO": "infomap_204_POTATO",
  "ADMIT": "infomap_1_SPEAK",
  "CULTIVATE": "infomap_137_CULTIVATE",
  "TRANSLATE": "infomap_46_COME BACK",
  "VULTURE": "infomap_148_VULTURE",
  "LOUSE": "infomap_229_LOUSE",
  "MOTHER": "infomap_160_MOTHER'S SISTER",
  "SUGAR CANE": "infomap_170_SUGAR",
  "PITY": "infomap_19_GRIEF",
  "BRAVE": "infomap_317_DARE",
  "ATTACK": "infomap_84_STRIKE OR BEAT",
  "DIVE": "infomap_45_SINK (DESCEND)",
  "GIVE": "infomap_88_GIVE",
  "BAY": "infomap_157_LAGOON",
  "CART": "infomap_115_CAR",
  "ROUGH (OF SEA)": "infomap_261_ROUGH (OF SEA)",
  "CLOTHES": "infomap_24_CLOTH",
  "MEAT": "infomap_104_FISH",
  "BE ABLE": "infomap_5_UNDERSTAND",
  "ACHE": "infomap_99_SICK",
  "BEGINNING": "infomap_62_FIRST",
  "PUPIL (STUDENT)": "infomap_316_PUPIL (STUDENT)",
  "DAUGHTER-IN-LAW (OF WOMAN)": "infomap_10_SON-IN-LAW (OF MAN)",
  "SICK": "infomap_99_SICK",
  "IMPROVE (SOMETHING)": "infomap_291_IMPROVE (SOMETHING)",
  "CRAWL": "infomap_51_RISE (MOVE UPWARDS)",
  "AREA": "infomap_9_COUNTRY",
  "ROOT": "infomap_167_TENDON",
  "SECOND": "infomap_164_SECOND",
  "GOAT": "infomap_64_SHEEP",
  "SWAMP": "infomap_139_SWAMP",
  "CHOKE": "infomap_45_SINK (DESCEND)",
  "NECK": "infomap_146_THROAT",
  "BREAK (CLEAVE)": "infomap_18_BREAK (CLEAVE)",
  "YOUNG MAN": "infomap_11_BOY",
  "RAG": "infomap_24_CLOTH",
  "SHIP": "infomap_80_CANOE",
  "EARLY": "infomap_116_MORNING",
  "DRIBBLE": "infomap_191_DRIBBLE",
  "COLLARBONE": "infomap_237_SHOULDER",
  "BEARD": "infomap_112_CHIN",
  "BECOME": "infomap_128_BECOME",
  "TOGETHER": "infomap_38_IMMEDIATELY",
  "ANCHOR": "infomap_184_HOOK",
  "PRESIDENT": "infomap_32_KING",
  "MAIZE": "infomap_7_GRAIN",
  "LINEN": "infomap_25_THREAD",
  "HOWL": "infomap_28_SHOUT",
  "RUG": "infomap_48_BLANKET",
  "TEAR (OF EYE)": "infomap_18_BREAK (CLEAVE)",
  "ADZE": "infomap_193_AXE",
  "POST": "infomap_2_WOOD",
  "FUR": "infomap_4_FUR",
  "BATTLE": "infomap_178_QUARREL",
  "FAN (OBJECT)": "infomap_127_BLOW (OF WIND)",
  "MOUSTACHE": "infomap_112_CHIN",
  "CHAIN": "infomap_207_NECKLACE",
  "ACCUSE": "infomap_14_FAULT",
  "RESULT IN": "infomap_128_BECOME",
  "SOUND (OF INSTRUMENT OR VOICE)": "infomap_43_CHIME (ACTION)",
  "HUNT": "infomap_21_GET",
  "BOWL": "infomap_98_BOWL",
  "CHILI PEPPER": "infomap_282_CHILI PEPPER",
  "ANT": "infomap_285_TERMITE",
  "FORWARD": "infomap_62_FIRST",
  "THOUGHT": "infomap_3_MIND",
  "RABBIT": "infomap_283_HARE",
  "FLOW": "infomap_70_RUN",
  "THRESH": "infomap_84_STRIKE OR BEAT",
  "YARD": "infomap_93_FENCE",
  "HEAP": "infomap_39_MOUNTAIN",
  "COAT": "infomap_48_BLANKET",
  "FEAR (FRIGHT)": "infomap_19_GRIEF",
  "FIREWOOD": "infomap_2_WOOD",
  "FORTRESS": "infomap_93_FENCE",
  "CORNER": "infomap_17_EDGE",
  "FLUTE": "infomap_122_BRASS INSTRUMENT (HORN OR TRUMPET)",
  "QUARREL": "infomap_178_QUARREL",
  "PART": "infomap_78_PART",
  "TWICE": "infomap_164_SECOND",
  "PEG": "infomap_325_PEG",
  "INSECT": "infomap_218_WORM",
  "TAKE": "infomap_21_GET",
  "ONCE (IN THE PAST)": "infomap_289_ONE TIME",
  "JAGUAR": "infomap_150_DOG",
  "WOOL": "infomap_4_FUR",
  "GUILTY": "infomap_14_FAULT",
  "WITH": "infomap_179_IN",
  "NAPE (OF NECK)": "infomap_146_THROAT",
  "MILK": "infomap_102_BREAST",
  "NIECE": "infomap_73_GRANDSON",
  "GRANDPARENTS": "infomap_33_OLD",
  "DAUGHTER": "infomap_11_BOY",
  "BUILD": "infomap_52_BUILD",
  "PIERCE": "infomap_72_WEAVE",
  "WOMAN": "infomap_58_WIFE",
  "DROWN": "infomap_45_SINK (DESCEND)",
  "CALL BY NAME": "infomap_28_SHOUT",
  "SHIRT": "infomap_24_CLOTH",
  "EXTINGUISH": "infomap_177_EXTINGUISH",
  "BLIND": "infomap_327_BLUNT",
  "SAME": "infomap_91_SEEM",
  "BORDER": "infomap_17_EDGE",
  "FRONT TOOTH (INCISOR)": "infomap_44_BEAK",
  "IMMEDIATELY": "infomap_38_IMMEDIATELY",
  "MALE (OF PERSON)": "infomap_96_MALE (OF PERSON)",
  "ARCH": "infomap_108_BOW",
  "STRAP": "infomap_158_STRAP",
  "WEST": "infomap_27_DARKNESS",
  "EVIL": "infomap_105_BAD",
  "TURN (SOMETHING)": "infomap_46_COME BACK",
  "SMALL": "infomap_181_SMALL",
  "FISHNET": "infomap_85_NETBAG",
  "ONLY": "infomap_210_ONLY",
  "BE HUNGRY": "infomap_149_HUNGER",
  "PUMA": "infomap_150_DOG",
  "OCEAN": "infomap_247_SEA",
  "DITCH": "infomap_40_HOLE",
  "HIGH TIDE": "infomap_206_TIDE",
  "SPECTACLES": "infomap_141_MIRROR",
  "GRANDMOTHER": "infomap_33_OLD",
  "LIGHT (WEIGHT)": "infomap_215_EASY",
  "BOSS": "infomap_234_HEAD",
  "DARE": "infomap_317_DARE",
  "CHANGE": "infomap_89_SELL",
  "HOT": "infomap_151_HEAT",
  "SWELL": "infomap_125_THICK",
  "VEIL": "infomap_24_CLOTH",
  "BORE": "infomap_156_HOLLOW OUT",
  "SPEAR": "infomap_108_BOW",
  "JUG": "infomap_163_POT",
  "TEMPLE": "infomap_216_TEMPLE",
  "NEAR": "infomap_17_EDGE",
  "SMOKE (EMIT SMOKE)": "infomap_121_FOG",
  "THIRST": "infomap_149_HUNGER",
  "TOWN": "infomap_302_VILLAGE",
  "SIMILAR": "infomap_91_SEEM",
  "CIRCLE": "infomap_83_CIRCLE",
  "END (OF TIME)": "infomap_174_LAST (FINAL)",
  "BELLY": "infomap_106_INTESTINES",
  "IN": "infomap_179_IN",
  "BUS": "infomap_115_CAR",
  "SLICE": "infomap_78_PART",
  "ROAD": "infomap_100_PATH",
  "SAY": "infomap_1_SPEAK",
  "STRIKE OR BEAT": "infomap_84_STRIKE OR BEAT",
  "NEPHEW": "infomap_73_GRANDSON",
  "WRITE": "infomap_117_DYE",
  "SAIL": "infomap_81_SWIM",
  "PRISONER": "infomap_123_PRISON",
  "ESCAPE": "infomap_70_RUN",
  "WORM": "infomap_218_WORM",
  "JAW": "infomap_112_CHIN",
  "THEN": "infomap_183_THEN",
  "VOICE": "infomap_1_SPEAK",
  "VINE": "infomap_25_THREAD",
  "THIS": "infomap_22_THAT",
  "BE SILENT": "infomap_142_QUIET",
  "OR": "infomap_20_ENOUGH",
  "RAM": "infomap_64_SHEEP",
  "MOTHER'S BROTHER": "infomap_152_FATHER'S BROTHER",
  "PHYSICIAN": "infomap_197_MAGICIAN",
  "POCKET": "infomap_85_NETBAG",
  "PAN": "infomap_163_POT",
  "I": "infomap_114_WE (INCLUSIVE)",
  "SIDE": "infomap_17_EDGE",
  "LAND (DESCEND)": "infomap_312_GO DOWN (DESCEND)",
  "THREAD": "infomap_25_THREAD",
  "MOTHER-IN-LAW (OF MAN)": "infomap_10_SON-IN-LAW (OF MAN)",
  "LISTEN": "infomap_5_UNDERSTAND",
  "FATHER-IN-LAW (OF MAN)": "infomap_10_SON-IN-LAW (OF MAN)",
  "SWEET": "infomap_170_SUGAR",
  "RAT": "infomap_290_MOUSE",
  "LIZARD": "infomap_286_LIZARD",
  "CARRY IN HAND": "infomap_66_CARRY",
  "FOOD": "infomap_53_DINNER (SUPPER)",
  "SPOIL (BECOME SPOILED)": "infomap_267_SPOIL (BECOME SPOILED)",
  "HORN (ANATOMY)": "infomap_122_BRASS INSTRUMENT (HORN OR TRUMPET)",
  "SILVER": "infomap_176_COIN",
  "SOLID": "infomap_42_HARD",
  "STINGY": "infomap_303_STINGY",
  "SWING (MOVEMENT)": "infomap_63_SHAKE",
  "AFTERWARDS": "infomap_183_THEN",
  "MALE": "infomap_96_MALE (OF PERSON)",
  "COOKHOUSE": "infomap_154_FIREPLACE",
  "HITHER (HERE TO)": "infomap_172_THERE",
  "FLEE": "infomap_70_RUN",
  "PICK": "infomap_18_BREAK (CLEAVE)",
  "SUMMIT": "infomap_308_SUMMIT",
  "TABLE": "infomap_135_BOARD",
  "ROAST OR FRY": "infomap_47_COOK (SOMETHING)",
  "THIN (OF SHAPE OF OBJECT)": "infomap_111_NARROW",
  "MISS (A TARGET)": "infomap_14_FAULT",
  "STRAIGHT": "infomap_6_CORRECT (RIGHT)",
  "GAP (DISTANCE)": "infomap_145_GAP (DISTANCE)",
  "BEGGAR": "infomap_217_POOR",
  "ZERO": "infomap_69_NOT",
  "KILL": "infomap_177_EXTINGUISH",
  "UGLY": "infomap_105_BAD",
  "BETRAY": "infomap_89_SELL",
  "EARTH (SOIL)": "infomap_9_COUNTRY",
  "SHIELD": "infomap_274_ARMOUR",
  "TOMORROW": "infomap_116_MORNING",
  "BONE": "infomap_8_LEG",
  "PREGNANT": "infomap_162_BEGET",
  "ANIMAL": "infomap_57_CATTLE",
  "GUN": "infomap_186_WEAPONS",
  "STORM": "infomap_87_BREATHE",
  "TIP (OF TONGUE)": "infomap_1_SPEAK",
  "ARSON": "infomap_143_LIGHT (IGNITE)",
  "SWAY": "infomap_63_SHAKE",
  "TIP (OF OBJECT)": "infomap_308_SUMMIT",
  "FOAM": "infomap_171_DUST",
  "SHOUT": "infomap_28_SHOUT",
  "SEED": "infomap_7_GRAIN",
  "ANSWER": "infomap_1_SPEAK",
  "BUTTOCKS": "infomap_8_LEG",
  "SUNDAY": "infomap_198_WEEK",
  "RAKE": "infomap_67_PITCHFORK",
  "MOUTH": "infomap_44_BEAK",
  "FORGET": "infomap_41_UNTIE",
  "ONE TIME": "infomap_289_ONE TIME",
  "LAUGHTER": "infomap_203_LAUGH",
  "CAR": "infomap_115_CAR",
  "WHITHER (WHERE TO)": "infomap_65_WHAT",
  "OPEN": "infomap_41_UNTIE",
  "MARRIED MAN": "infomap_58_WIFE",
  "RELATIVES": "infomap_30_RELATIVES",
  "BE ALIVE": "infomap_16_REMAIN",
  "CITRUS FRUIT": "infomap_76_SALTY",
  "ACORN": "infomap_279_OAK",
  "TIRED": "infomap_49_SMOOTH",
  "GET": "infomap_21_GET",
  "AGE": "infomap_107_SUMMER",
  "VISIBLE": "infomap_91_SEEM",
  "LEAF": "infomap_309_LEAF (LEAFLIKE OBJECT)",
  "BOAR": "infomap_195_SOW (FEMALE PIG)",
  "PUT ON": "infomap_314_PUT ON",
  "IN FRONT OF": "infomap_62_FIRST",
  "MANIOC BREAD": "infomap_298_CASSAVA",
  "SHARK": "infomap_281_WHALE",
  "ANCESTORS": "infomap_33_OLD",
  "RULE": "infomap_209_SEND",
  "URGE (SOMEONE)": "infomap_319_DRIVE (CATTLE)",
  "FROST": "infomap_124_FROST",
  "PUBIC HAIR": "infomap_4_FUR",
  "SINK (DISAPPEAR IN WATER)": "infomap_45_SINK (DESCEND)",
  "KIDNEY": "infomap_275_KIDNEY",
  "WHITE-LIPPED PECCARY": "infomap_296_WHITE-LIPPED PECCARY",
  "CHAT (WITH SOMEBODY)": "infomap_1_SPEAK",
  "BAIT": "infomap_53_DINNER (SUPPER)",
  "SPREAD OUT": "infomap_168_STRETCH",
  "INNOCENT": "infomap_12_LIGHT (RADIATION)",
  "CORRECT (RIGHT)": "infomap_6_CORRECT (RIGHT)",
  "NUT": "infomap_7_GRAIN",
  "SNOW": "infomap_213_SNOW",
  "HARVEST": "infomap_7_GRAIN",
  "GIRL": "infomap_11_BOY",
  "ASH": "infomap_171_DUST",
  "BUTTER": "infomap_75_FAT (ORGANIC SUBSTANCE)",
  "HEART": "infomap_3_MIND",
  "FAT (OBESE)": "infomap_75_FAT (ORGANIC SUBSTANCE)",
  "NIT": "infomap_229_LOUSE",
  "SOUND OR NOISE": "infomap_1_SPEAK",
  "LIGHT (RADIATION)": "infomap_12_LIGHT (RADIATION)",
  "CURASSOW": "infomap_277_GUAN",
  "PASS": "infomap_128_BECOME",
  "HARD": "infomap_42_HARD",
  "DOUGH": "infomap_236_FLOUR",
  "RYE": "infomap_7_GRAIN",
  "SIEVE": "infomap_77_SQUEEZE",
  "DAY (NOT NIGHT)": "infomap_35_TIME",
  "SPOON": "infomap_67_PITCHFORK",
  "THATCH": "infomap_232_THATCH",
  "LOUD": "infomap_42_HARD",
  "FAR": "infomap_13_HIGH",
  "GOOSE": "infomap_310_DUCK",
  "COLLARED PECCARY": "infomap_296_WHITE-LIPPED PECCARY",
  "NOT": "infomap_69_NOT",
  "THINK": "infomap_5_UNDERSTAND",
  "CHIMNEY": "infomap_122_BRASS INSTRUMENT (HORN OR TRUMPET)",
  "WISE": "infomap_301_WISE",
  "SLEEP": "infomap_134_SLEEP",
  "YOUNG": "infomap_11_BOY",
  "DISTURB": "infomap_194_DISTURB",
  "STAB": "infomap_156_HOLLOW OUT",
  "TORCH OR LAMP": "infomap_129_CANDLE",
  "INVITE": "infomap_28_SHOUT",
  "PAINT (PIGMENTS)": "infomap_117_DYE",
  "PLAIT": "infomap_72_WEAVE",
  "DO OR MAKE": "infomap_52_BUILD",
  "STILL (CONTINUING)": "infomap_20_ENOUGH",
  "BULL": "infomap_57_CATTLE",
  "DRY": "infomap_69_NOT",
  "FLOUR": "infomap_236_FLOUR",
  "FULL": "infomap_125_THICK",
  "ASK (REQUEST)": "infomap_61_ASK (REQUEST)",
  "MIX": "infomap_235_MIX",
  "ENOUGH": "infomap_20_ENOUGH",
  "LEG": "infomap_8_LEG",
  "POUR": "infomap_238_CAST",
  "READ": "infomap_23_COUNT",
  "ORPHAN": "infomap_217_POOR",
  "SUMMER": "infomap_107_SUMMER",
  "OLD (AGED)": "infomap_33_OLD",
  "MONTH": "infomap_251_MOON",
  "LOAD": "infomap_311_LOAD",
  "HOLY": "infomap_12_LIGHT (RADIATION)",
  "BAMBOO": "infomap_122_BRASS INSTRUMENT (HORN OR TRUMPET)",
  "WINE": "infomap_101_WINE",
  "HOUR": "infomap_35_TIME",
  "RECOGNIZE (SOMEBODY)": "infomap_5_UNDERSTAND",
  "GUARD": "infomap_26_PRESERVE",
  "FATHER'S SISTER": "infomap_160_MOTHER'S SISTER",
  "FLOOR": "infomap_9_COUNTRY",
  "BACK (DIRECTION)": "infomap_257_BACKWARD",
  "OFTEN": "infomap_132_OFTEN",
  "WATERFALL": "infomap_299_WATERFALL",
  "SPEAK": "infomap_1_SPEAK",
  "SPIN": "infomap_59_TWIST",
  "CUSTOM": "infomap_212_CUSTOM",
  "MAINLAND": "infomap_9_COUNTRY",
  "SWELLING": "infomap_90_WOUND",
  "AMOUNT": "infomap_264_COUNT (QUANTITY)",
  "YOUNGER BROTHER": "infomap_15_YOUNGER BROTHER",
  "GOURD": "infomap_313_GOURD",
  "CHIME (ACTION)": "infomap_43_CHIME (ACTION)",
  "COOK (SOMETHING)": "infomap_47_COOK (SOMETHING)",
  "LIGHT (COLOR)": "infomap_12_LIGHT (RADIATION)",
  "BUSINESS": "infomap_305_SHOP",
  "MEMORY": "infomap_3_MIND",
  "DO": "infomap_52_BUILD",
  "MALE (OF ANIMAL)": "infomap_96_MALE (OF PERSON)",
  "UNTIE": "infomap_41_UNTIE",
  "RINSE": "infomap_81_SWIM",
  "WEAPONS": "infomap_186_WEAPONS",
  "LEASH": "infomap_158_STRAP",
  "STONE OR ROCK": "infomap_95_STONE OR ROCK",
  "COME BACK": "infomap_46_COME BACK",
  "HIGH": "infomap_13_HIGH",
  "COTTON": "infomap_25_THREAD",
  "HEADBAND": "infomap_222_HELMET",
  "BEAM": "infomap_187_RAFTER",
  "ELECTRICITY": "infomap_12_LIGHT (RADIATION)",
  "BE": "infomap_16_REMAIN",
  "POOR": "infomap_217_POOR",
  "HALF": "infomap_78_PART",
  "SCAR": "infomap_90_WOUND",
  "SOME": "infomap_181_SMALL",
  "BUTTON": "infomap_173_KNOT",
  "CHAIR": "infomap_135_BOARD",
  "BARKING": "infomap_166_SCOLD",
  "STAND UP": "infomap_86_STAND",
  "PLAIN": "infomap_37_FIELD",
  "MAT": "infomap_48_BLANKET",
  "CANDY": "infomap_110_HONEY",
  "GARDEN": "infomap_37_FIELD",
  "AGAIN": "infomap_20_ENOUGH",
  "BEGIN": "infomap_62_FIRST",
  "SINK (DESCEND)": "infomap_45_SINK (DESCEND)",
  "NEED (NOUN)": "infomap_113_WANT",
  "MORNING": "infomap_116_MORNING",
  "GREY": "infomap_97_GREEN",
  "SHELL": "infomap_241_SHELL",
  "FEED": "infomap_320_FEED",
  "TUMBLE (FALL DOWN)": "infomap_190_FALL",
  "LAME": "infomap_263_LIMP",
  "OMEN": "infomap_19_GRIEF",
  "VEGETABLES": "infomap_7_GRAIN",
  "HOME": "infomap_56_HOUSE",
  "MEET": "infomap_74_SEE",
  "HARE": "infomap_283_HARE",
  "PINCH": "infomap_77_SQUEEZE",
  "SKY": "infomap_243_SKY",
  "WIFE": "infomap_58_WIFE",
  "BASKET": "infomap_85_NETBAG",
  "SHAKE": "infomap_63_SHAKE",
  "ALWAYS": "infomap_132_OFTEN",
  "POT": "infomap_163_POT",
  "IMITATE": "infomap_23_COUNT",
  "DOWN OR BELOW": "infomap_36_LOW",
  "BROTHER": "infomap_15_YOUNGER BROTHER",
  "STOMACH": "infomap_106_INTESTINES",
  "TRUE": "infomap_6_CORRECT (RIGHT)",
  "PASTURE": "infomap_37_FIELD",
  "TESTICLES": "infomap_256_TESTICLES",
  "JOIN": "infomap_82_TIE",
  "EAGLE": "infomap_148_VULTURE",
  "WARE": "infomap_225_ITEM",
  "CROW": "infomap_148_VULTURE",
  "FIRST": "infomap_62_FIRST",
  "LOOK FOR": "infomap_74_SEE",
  "NEIGHBOUR": "infomap_30_RELATIVES",
  "CLEVER": "infomap_301_WISE",
  "BIG": "infomap_125_THICK",
  "PIN": "infomap_118_NEEDLE (FOR SEWING)",
  "CLUB": "infomap_2_WOOD",
  "TALL": "infomap_13_HIGH",
  "BEGET": "infomap_162_BEGET",
  "COLD (OF WEATHER)": "infomap_221_FRESH",
  "SKIRT": "infomap_24_CLOTH",
  "KEEP": "infomap_26_PRESERVE",
  "INJECTION": "infomap_118_NEEDLE (FOR SEWING)",
  "GATHER": "infomap_109_PICK UP",
  "HE": "infomap_22_THAT",
  "INTESTINES": "infomap_106_INTESTINES",
  "KNOW (SOMETHING)": "infomap_5_UNDERSTAND",
  "TASTY": "infomap_170_SUGAR",
  "HELL": "infomap_130_FIRE",
  "BEAD": "infomap_207_NECKLACE",
  "BUNCH": "infomap_173_KNOT",
  "BLOW (WITH MOUTH)": "infomap_127_BLOW (OF WIND)",
  "STUPID": "infomap_144_MUTE",
  "SLOW": "infomap_120_BE LATE",
  "GILL": "infomap_219_EAR",
  "GRASS-SKIRT": "infomap_24_CLOTH",
  "CAST": "infomap_238_CAST",
  "LATCH": "infomap_147_LATCH",
  "FURROW": "infomap_40_HOLE",
  "BRUISE": "infomap_90_WOUND",
  "ROLL": "infomap_46_COME BACK",
  "BREAKFAST": "infomap_53_DINNER (SUPPER)",
  "SOFT": "infomap_49_SMOOTH",
  "TORTOISE": "infomap_271_TORTOISE",
  "DOUBT": "infomap_71_THINK (REFLECT)",
  "LIGHT (IGNITE)": "infomap_143_LIGHT (IGNITE)",
  "GRANDDAUGHTER": "infomap_73_GRANDSON",
  "LAND": "infomap_9_COUNTRY",
  "THINK (REFLECT)": "infomap_71_THINK (REFLECT)",
  "SWING (SOMETHING)": "infomap_63_SHAKE",
  "COVER": "infomap_252_SHUT",
  "CALL": "infomap_28_SHOUT",
  "ANXIETY": "infomap_19_GRIEF",
  "VAGINA": "infomap_260_VULVA",
  "TWIST": "infomap_59_TWIST",
  "AWL": "infomap_118_NEEDLE (FOR SEWING)",
  "DOORPOST": "infomap_2_WOOD",
  "STICK": "infomap_2_WOOD",
  "SAILCLOTH": "infomap_129_CANDLE",
  "IDOL": "infomap_208_IDOL",
  "STREET": "infomap_100_PATH",
  "BLAME": "infomap_14_FAULT",
  "COURT": "infomap_119_ADJUDICATE",
  "CHICKEN": "infomap_103_FOWL",
  "FOREST": "infomap_2_WOOD",
  "ROT": "infomap_267_SPOIL (BECOME SPOILED)",
  "WEATHER": "infomap_35_TIME",
  "STOVE": "infomap_154_FIREPLACE",
  "FAMINE": "infomap_149_HUNGER",
  "SOLDIER": "infomap_262_SOLDIER",
  "SHARP": "infomap_249_POINTED",
  "YOUNGER SIBLING": "infomap_15_YOUNGER BROTHER",
  "PATH OR ROAD": "infomap_100_PATH",
  "OWN": "infomap_242_HAVE",
  "FEW": "infomap_181_SMALL",
  "AT THAT TIME": "infomap_183_THEN",
  "SUDDENLY": "infomap_38_IMMEDIATELY",
  "CARCASS": "infomap_68_DIE",
  "DEFENDANT": "infomap_14_FAULT",
  "CAUSE": "infomap_165_BECAUSE",
  "PARENTS-IN-LAW": "infomap_10_SON-IN-LAW (OF MAN)",
  "EMBERS": "infomap_246_EMBERS",
  "CROUCH": "infomap_16_REMAIN",
  "ORNAMENT": "infomap_95_STONE OR ROCK",
  "BURN (SOMETHING)": "infomap_143_LIGHT (IGNITE)",
  "FOREIGN": "infomap_164_SECOND",
  "APPROACH": "infomap_192_COME",
  "MIDDLE": "infomap_78_PART",
  "BAD": "infomap_105_BAD",
  "PORT": "infomap_157_LAGOON",
  "PIT (POTHOLE)": "infomap_40_HOLE",
  "WHISTLE": "infomap_127_BLOW (OF WIND)",
  "GRAVE": "infomap_40_HOLE",
  "HELMET": "infomap_222_HELMET",
  "BOW": "infomap_108_BOW",
  "LEARN": "infomap_175_STUDY",
  "REST": "infomap_87_BREATHE",
  "YOUNGER SISTER": "infomap_15_YOUNGER BROTHER",
  "GIVE BACK": "infomap_46_COME BACK",
  "NARROW": "infomap_111_NARROW",
  "NASAL MUCUS (SNOT)": "infomap_131_COMMON COLD (DISEASE)",
  "PEN": "infomap_4_FUR",
  "BRIDGE": "infomap_258_LADDER",
  "PRECIPICE": "infomap_95_STONE OR ROCK",
  "INTENTION": "infomap_3_MIND",
  "FOLD": "infomap_59_TWIST",
  "PUMPKIN": "infomap_313_GOURD",
  "GRASS": "infomap_37_FIELD",
  "LEND": "infomap_88_GIVE",
  "HAIR (HEAD)": "infomap_323_HAIR (HEAD)",
  "FAULT": "infomap_14_FAULT",
  "BEE": "infomap_110_HONEY",
  "CUP": "infomap_98_BOWL",
  "DESTROY": "infomap_18_BREAK (CLEAVE)",
  "POTATO": "infomap_204_POTATO",
  "DRIP (EMIT LIQUID)": "infomap_191_DRIBBLE",
  "MAGIC": "infomap_197_MAGICIAN",
  "SAGO PALM": "infomap_232_THATCH",
  "GOD": "infomap_32_KING",
  "LOWER LEG": "infomap_8_LEG",
  "TOOTH": "infomap_44_BEAK",
  "SON": "infomap_11_BOY",
  "FEVER": "infomap_151_HEAT",
  "WE TWO (INCLUSIVE)": "infomap_114_WE (INCLUSIVE)",
  "DONKEY": "infomap_79_HORSE",
  "WET": "infomap_324_WET",
  "GRANDSON": "infomap_73_GRANDSON",
  "LIMP": "infomap_263_LIMP",
  "RETREAT": "infomap_70_RUN",
  "GUAN": "infomap_277_GUAN",
  "FOR A LONG TIME": "infomap_13_HIGH",
  "DIRTY": "infomap_27_DARKNESS",
  "FINE (PENALTY)": "infomap_315_FINE (PENALTY)",
  "PRICE": "infomap_126_EXPENSIVE",
  "SALT": "infomap_76_SALTY",
  "RUB": "infomap_94_SWEEP",
  "NAIL (TOOL)": "infomap_325_PEG",
  "SAP": "infomap_31_WATER",
  "DARKNESS": "infomap_27_DARKNESS",
  "PILL": "infomap_161_MEDICINE",
  "CAMPFIRE": "infomap_130_FIRE",
  "SEIZE": "infomap_21_GET",
  "HEAVEN": "infomap_243_SKY",
  "PINE": "infomap_297_FIR",
  "SUSPECT": "infomap_71_THINK (REFLECT)",
  "SWEEP": "infomap_94_SWEEP",
  "DENY": "infomap_138_FORBID",
  "COMMON COLD (DISEASE)": "infomap_131_COMMON COLD (DISEASE)",
  "BESIDE": "infomap_17_EDGE",
  "SQUEEZE": "infomap_77_SQUEEZE",
  "SMOOTH": "infomap_49_SMOOTH",
  "MUMBLE": "infomap_199_MUMBLE",
  "ARMY": "infomap_262_SOLDIER",
  "CONNECT": "infomap_82_TIE",
  "CRY": "infomap_28_SHOUT",
  "COMB": "infomap_205_COMB",
  "BEND (SOMETHING)": "infomap_59_TWIST",
  "MISTAKE": "infomap_14_FAULT",
  "KICK": "infomap_84_STRIKE OR BEAT",
  "SOON": "infomap_38_IMMEDIATELY",
  "MOUSE": "infomap_290_MOUSE",
  "STUDY": "infomap_175_STUDY",
  "NO": "infomap_69_NOT",
  "SMILE": "infomap_203_LAUGH",
  "RICE": "infomap_7_GRAIN",
  "BELT": "infomap_158_STRAP",
  "ASK (INQUIRE)": "infomap_61_ASK (REQUEST)",
  "PAIR": "infomap_185_PAIR",
  "COME": "infomap_192_COME",
  "ARROW": "infomap_108_BOW",
  "BOTTOM": "infomap_36_LOW",
  "REEF": "infomap_95_STONE OR ROCK",
  "WORK (LABOUR)": "infomap_52_BUILD",
  "PUSH": "infomap_2_WOOD",
  "MOUNTAIN": "infomap_39_MOUNTAIN",
  "SPADE": "infomap_182_SPADE",
  "FOAL": "infomap_79_HORSE",
  "CAUSE TO (LET)": "infomap_88_GIVE",
  "BOLT (OF LIGHTNING)": "infomap_155_THUNDER",
  "BODY": "infomap_68_DIE",
  "SIBLING": "infomap_15_YOUNGER BROTHER",
  "FLAME": "infomap_130_FIRE",
  "WHALE": "infomap_281_WHALE",
  "DRIVE (CATTLE)": "infomap_319_DRIVE (CATTLE)",
  "ANKLE": "infomap_8_LEG",
  "BILL": "infomap_227_DEBT",
  "EGG": "infomap_256_TESTICLES",
  "LICK": "infomap_34_DRINK",
  "FIND": "infomap_74_SEE",
  "CHISEL": "infomap_269_CHISEL",
  "HEAD": "infomap_234_HEAD",
  "GOOD-LOOKING": "infomap_6_CORRECT (RIGHT)",
  "DRESS": "infomap_24_CLOTH",
  "QUIET": "infomap_142_QUIET",
  "OLDER BROTHER": "infomap_15_YOUNGER BROTHER",
  "MEANING": "infomap_3_MIND",
  "SMELL (STINK)": "infomap_55_STINKING",
  "GROAN": "infomap_28_SHOUT",
  "MEASURE": "infomap_23_COUNT",
  "WEEK": "infomap_198_WEEK",
  "TEAR (SHRED)": "infomap_18_BREAK (CLEAVE)",
  "WAIT (FOR)": "infomap_16_REMAIN",
  "SNAKE": "infomap_218_WORM",
  "BED": "infomap_48_BLANKET",
  "PAW": "infomap_136_FINGERNAIL",
  "DECEIT": "infomap_189_DECEIT",
  "KNIT": "infomap_82_TIE",
  "ROUND": "infomap_83_CIRCLE",
  "EYELASH": "infomap_196_EYELASH",
  "WRAP": "infomap_59_TWIST",
  "CAPE": "infomap_44_BEAK",
  "YESTERDAY": "infomap_116_MORNING",
  "LEAF (LEAFLIKE OBJECT)": "infomap_309_LEAF (LEAFLIKE OBJECT)",
  "CARVE": "infomap_60_CUT",
  "THEY": "infomap_22_THAT",
  "WE": "infomap_114_WE (INCLUSIVE)",
  "CURSE": "infomap_166_SCOLD",
  "HAVE": "infomap_242_HAVE",
  "NOISE": "infomap_1_SPEAK",
  "GREEN": "infomap_97_GREEN",
  "WORLD": "infomap_9_COUNTRY",
  "CLOCK": "infomap_35_TIME",
  "HAIR (BODY)": "infomap_4_FUR",
  "CLAY": "infomap_139_SWAMP",
  "LOVE": "infomap_113_WANT",
  "SCORPION": "infomap_293_CENTIPEDE",
  "BRACELET": "infomap_83_CIRCLE",
  "KING": "infomap_32_KING",
  "SONG": "infomap_92_SING",
  "RAW": "infomap_97_GREEN",
  "FOG": "infomap_121_FOG",
  "FOWL": "infomap_103_FOWL",
  "KID": "infomap_64_SHEEP",
  "PLAY": "infomap_92_SING",
  "DAMP": "infomap_324_WET",
  "COUSIN": "infomap_15_YOUNGER BROTHER",
  "READY": "infomap_20_ENOUGH",
  "YEAR": "infomap_107_SUMMER",
  "HAPPY": "infomap_6_CORRECT (RIGHT)",
  "HEALTHY": "infomap_6_CORRECT (RIGHT)",
  "THUNDER (VERB)": "infomap_155_THUNDER",
  "TREE STUMP": "infomap_2_WOOD",
  "COUGH": "infomap_131_COMMON COLD (DISEASE)",
  "HEEL": "infomap_8_LEG",
  "CATTLE": "infomap_57_CATTLE",
  "SKIN": "infomap_4_FUR",
  "STING": "infomap_2_WOOD",
  "DEAR": "infomap_126_EXPENSIVE",
  "SHIT (DEFECATE)": "infomap_295_SHIT (DEFECATE)",
  "BEER": "infomap_101_WINE",
  "GUEST": "infomap_32_KING",
  "SMOKE (INHALE)": "infomap_34_DRINK",
  "CHOOSE": "infomap_109_PICK UP",
  "QUEEN": "infomap_32_KING",
  "DOG": "infomap_150_DOG",
  "GLUE": "infomap_31_WATER",
  "RAIN (RAINING)": "infomap_31_WATER",
  "AT FIRST": "infomap_62_FIRST",
  "ANGER": "infomap_240_HATE",
  "BECOME SICK": "infomap_99_SICK",
  "COOKED": "infomap_50_YELLOW",
  "ROUGH": "infomap_42_HARD",
  "FLY (INSECT)": "infomap_220_MOSQUITO",
  "TREE TRUNK": "infomap_2_WOOD",
  "HALT (STOP)": "infomap_86_STAND",
  "BLANKET": "infomap_48_BLANKET",
  "CONDEMN": "infomap_119_ADJUDICATE",
  "STRING": "infomap_158_STRAP",
  "TURN": "infomap_46_COME BACK",
  "BAD LUCK": "infomap_19_GRIEF",
  "STORM CLOUDS": "infomap_121_FOG",
  "PAINTING": "infomap_117_DYE",
  "BOLT (MOVE IN HASTE)": "infomap_159_DASH (OF VEHICLE)",
  "STEPMOTHER": "infomap_10_SON-IN-LAW (OF MAN)",
  "BREATHE": "infomap_87_BREATHE",
  "BOOK": "infomap_140_LETTER",
  "DUST": "infomap_171_DUST",
  "HOOK": "infomap_184_HOOK",
  "COLD": "infomap_124_FROST",
  "BRUSH": "infomap_205_COMB",
  "SHORT": "infomap_36_LOW",
  "HAND": "infomap_29_ARM",
  "SNIFF": "infomap_55_STINKING",
  "OLD": "infomap_33_OLD",
  "STORY": "infomap_153_STORY",
  "SNEEZE": "infomap_131_COMMON COLD (DISEASE)",
  "STUTTER": "infomap_199_MUMBLE",
  "EYEBROW": "infomap_196_EYELASH",
  "BRANCH": "infomap_67_PITCHFORK",
  "GRIEF": "infomap_19_GRIEF",
  "STAND": "infomap_86_STAND",
  "SEEM": "infomap_91_SEEM",
  "FENCE": "infomap_93_FENCE",
  "LENGTH": "infomap_13_HIGH",
  "WAVE": "infomap_261_ROUGH (OF SEA)",
  "DENSE": "infomap_132_OFTEN",
  "DRESS UP": "infomap_314_PUT ON",
  "BARLEY": "infomap_7_GRAIN",
  "FORBID": "infomap_138_FORBID",
  "FEMALE": "infomap_58_WIFE",
  "PLANT (SOMETHING)": "infomap_137_CULTIVATE",
  "BATTLE-AXE": "infomap_193_AXE",
  "SEND": "infomap_209_SEND",
  "SIT DOWN": "infomap_16_REMAIN",
  "WARM": "infomap_151_HEAT",
  "BEAUTIFUL": "infomap_6_CORRECT (RIGHT)",
  "WASP": "infomap_110_HONEY",
  "STEPDAUGHTER": "infomap_307_STEPDAUGHTER",
  "BUY": "infomap_89_SELL",
  "PRAISE": "infomap_61_ASK (REQUEST)",
  "DISH": "infomap_98_BOWL",
  "DANCE": "infomap_92_SING",
  "BOTTLE": "infomap_141_MIRROR",
  "DUCK": "infomap_310_DUCK",
  "BEFORE": "infomap_62_FIRST",
  "UPPER ARM": "infomap_250_LOWER ARM",
  "EARWAX": "infomap_129_CANDLE",
  "HAVE SEX": "infomap_233_MARRY",
  "BLISTER": "infomap_90_WOUND",
  "CAT": "infomap_150_DOG",
  "WORD": "infomap_1_SPEAK",
  "BRIGHT": "infomap_12_LIGHT (RADIATION)",
  "PROTECT": "infomap_26_PRESERVE",
  "TEACH": "infomap_175_STUDY",
  "PICK UP": "infomap_109_PICK UP",
  "CORN FIELD": "infomap_37_FIELD",
  "DAWN": "infomap_116_MORNING",
  "FALL ASLEEP": "infomap_134_SLEEP",
  "FLESH": "infomap_104_FISH",
  "KNOT": "infomap_173_KNOT",
  "FRINGE": "infomap_17_EDGE",
  "THING": "infomap_225_ITEM",
  "SANDFLY": "infomap_220_MOSQUITO",
  "WHISPER": "infomap_199_MUMBLE",
  "VALLEY": "infomap_37_FIELD",
  "HEADGEAR": "infomap_222_HELMET",
  "TRAP (PITFALL)": "infomap_85_NETBAG",
  "BURY": "infomap_169_HIDE (CONCEAL)",
  "HATE": "infomap_240_HATE",
  "WE (INCLUSIVE)": "infomap_114_WE (INCLUSIVE)",
  "PULL OFF (SKIN)": "infomap_245_PEEL",
  "FATHOM": "infomap_29_ARM",
  "CHILD (YOUNG HUMAN)": "infomap_11_BOY",
  "BOIL (SOMETHING)": "infomap_47_COOK (SOMETHING)",
  "SIBLING'S CHILD": "infomap_73_GRANDSON",
  "OLD MAN": "infomap_33_OLD",
  "PREVENT": "infomap_138_FORBID",
  "PENIS": "infomap_328_TAIL",
  "KNOCK": "infomap_43_CHIME (ACTION)",
  "OATH": "infomap_224_SWEAR",
  "WASH": "infomap_81_SWIM",
  "FINISH": "infomap_86_STAND",
  "HOE": "infomap_182_SPADE",
  "CUT DOWN": "infomap_60_CUT",
  "ADJUDICATE": "infomap_119_ADJUDICATE",
  "STRENGTH": "infomap_201_VIOLENCE",
  "HOW MANY": "infomap_248_HOW MANY",
  "CAVE": "infomap_40_HOLE",
  "ICE": "infomap_213_SNOW",
  "LADDER": "infomap_258_LADDER",
  "MEN'S HOUSE": "infomap_56_HOUSE",
  "THAW (DEW)": "infomap_273_THAW (DEW)",
  "LOW TIDE": "infomap_206_TIDE",
  "MEAL": "infomap_53_DINNER (SUPPER)",
  "CORPSE": "infomap_68_DIE",
  "SNAIL": "infomap_241_SHELL",
  "FIELD": "infomap_37_FIELD",
  "PESTLE": "infomap_226_MORTAR CRUSHER",
  "INCREASE": "infomap_51_RISE (MOVE UPWARDS)",
  "GOLD": "infomap_50_YELLOW",
  "BEESWAX": "infomap_129_CANDLE",
  "CERTAIN": "infomap_6_CORRECT (RIGHT)",
  "INSIDE": "infomap_36_LOW",
  "HOLE": "infomap_40_HOLE",
  "CASSAVA": "infomap_298_CASSAVA",
  "BITE": "infomap_34_DRINK",
  "PRESERVE": "infomap_26_PRESERVE",
  "CALF": "infomap_57_CATTLE",
  "SEA": "infomap_247_SEA",
  "OINTMENT": "infomap_75_FAT (ORGANIC SUBSTANCE)",
  "FAMILY": "infomap_30_RELATIVES",
  "THREE": "infomap_287_THIRD",
  "JEWEL": "infomap_95_STONE OR ROCK",
  "DIVORCE": "infomap_228_THROW",
  "WANT": "infomap_113_WANT",
  "SOW (FEMALE PIG)": "infomap_195_SOW (FEMALE PIG)",
  "DRAW MILK": "infomap_77_SQUEEZE",
  "COAST": "infomap_17_EDGE",
  "DYE": "infomap_117_DYE",
  "BARK": "infomap_4_FUR",
  "SHINE": "infomap_12_LIGHT (RADIATION)",
  "YELLOW": "infomap_50_YELLOW",
  "THROAT": "infomap_146_THROAT",
  "OLDER SISTER": "infomap_15_YOUNGER BROTHER",
  "ROCK": "infomap_39_MOUNTAIN",
  "CHANGE (BECOME DIFFERENT)": "infomap_89_SELL",
  "SPRINGTIME": "infomap_107_SUMMER",
  "STEPSON": "infomap_307_STEPDAUGHTER",
  "MUSIC": "infomap_92_SING",
  "KNEAD": "infomap_235_MIX",
  "POSTCARD": "infomap_140_LETTER",
  "DREAM": "infomap_265_DREAM",
  "DEAF": "infomap_144_MUTE",
  "FRIEND": "infomap_30_RELATIVES",
  "ALCOHOL (FERMENTED DRINK)": "infomap_101_WINE",
  "NOOSE": "infomap_173_KNOT",
  "LAUGH": "infomap_203_LAUGH",
  "GROUND": "infomap_9_COUNTRY",
  "SCALE": "infomap_241_SHELL",
  "SHORE": "infomap_17_EDGE",
  "BURN": "infomap_284_ROAST (SOMETHING)",
  "DAY BEFORE YESTERDAY": "infomap_288_DAY BEFORE YESTERDAY",
  "HAPPEN": "infomap_128_BECOME",
  "HE OR SHE": "infomap_22_THAT",
  "BLOOD VESSEL": "infomap_167_TENDON",
  "PATH": "infomap_100_PATH",
  "SATURDAY": "infomap_198_WEEK",
  "BUNDLE": "infomap_82_TIE",
  "SPINDLE": "infomap_278_AXLE",
  "WHEN": "infomap_165_BECAUSE",
  "WATCH": "infomap_74_SEE",
  "ROAST (SOMETHING)": "infomap_284_ROAST (SOMETHING)",
  "SMOKE (EXHAUST)": "infomap_121_FOG",
  "SAUCER": "infomap_98_BOWL",
  "BE LATE": "infomap_120_BE LATE",
  "KNIFE": "infomap_133_KNIFE",
  "WALL (OF HOUSE)": "infomap_93_FENCE",
  "SAW": "infomap_60_CUT",
  "SCRATCH": "infomap_94_SWEEP",
  "HEAD LOUSE": "infomap_294_HEAD LOUSE",
  "MOTHER'S SISTER": "infomap_160_MOTHER'S SISTER",
  "HEN": "infomap_103_FOWL",
  "LIFE": "infomap_16_REMAIN",
  "WIPE": "infomap_94_SWEEP",
  "SHE": "infomap_22_THAT",
  "WINDOW": "infomap_239_DOOR",
  "MANNER": "infomap_212_CUSTOM",
  "FIVE": "infomap_29_ARM",
  "WHEEL": "infomap_83_CIRCLE",
  "ROOF": "infomap_232_THATCH",
  "BURNING": "infomap_143_LIGHT (IGNITE)",
  "GO": "infomap_54_WALK",
  "BECAUSE": "infomap_165_BECAUSE",
  "EARN": "infomap_21_GET",
  "YOU": "infomap_322_YOU",
  "TOBACCO": "infomap_300_CIGARETTE",
  "PEOPLE": "infomap_30_RELATIVES",
  "FRAGRANT": "infomap_55_STINKING",
  "TOOL": "infomap_186_WEAPONS",
  "JOY": "infomap_292_HAPPINESS",
  "NATIVE COUNTRY": "infomap_9_COUNTRY",
  "ARRIVE": "infomap_192_COME",
  "CARRY ON SHOULDER": "infomap_66_CARRY",
  "LIE (MISLEAD)": "infomap_189_DECEIT",
  "THOU": "infomap_322_YOU",
  "FAN ACTION": "infomap_127_BLOW (OF WIND)",
  "PUS": "infomap_55_STINKING",
  "BACK": "infomap_223_BACK",
  "HAY": "infomap_37_FIELD",
  "DASH (OF VEHICLE)": "infomap_159_DASH (OF VEHICLE)",
  "REMAIN": "infomap_16_REMAIN",
  "PREACH": "infomap_1_SPEAK",
  "CHIEFTAIN": "infomap_32_KING",
  "NOSE": "infomap_44_BEAK",
  "MOORLAND": "infomap_139_SWAMP",
  "HOW": "infomap_65_WHAT",
  "BELIEVE": "infomap_5_UNDERSTAND",
  "RAPIDS": "infomap_299_WATERFALL",
  "MOTHER-IN-LAW (OF WOMAN)": "infomap_10_SON-IN-LAW (OF MAN)",
  "DEMON": "infomap_3_MIND",
  "SLAB": "infomap_135_BOARD",
  "EYELID": "infomap_196_EYELASH",
  "FAITHFUL": "infomap_6_CORRECT (RIGHT)",
  "VICTORY": "infomap_306_DEFEAT",
  "PUNISHMENT": "infomap_315_FINE (PENALTY)",
  "FOLLOW": "infomap_259_PURSUE",
  "CHARCOAL": "infomap_246_EMBERS",
  "LIP": "infomap_44_BEAK",
  "WEAK": "infomap_49_SMOOTH",
  "BRASS INSTRUMENT (HORN OR TRUMPET)": "infomap_122_BRASS INSTRUMENT (HORN OR TRUMPET)",
  "FINGERNAIL OR TOENAIL": "infomap_136_FINGERNAIL",
  "WAKE UP": "infomap_86_STAND",
  "HOLLOW OUT": "infomap_156_HOLLOW OUT",
  "POWER": "infomap_201_VIOLENCE",
  "MASON": "infomap_272_MASON",
  "WHEAT": "infomap_7_GRAIN",
  "PADDLE": "infomap_188_ROW",
  "SPLASH": "infomap_230_JUMP",
  "RAFTER": "infomap_187_RAFTER",
  "BOTHER (HARASS)": "infomap_194_DISTURB",
  "FALL": "infomap_190_FALL",
  "STRETCH": "infomap_168_STRETCH",
  "STABLE": "infomap_123_PRISON",
  "MOUNTAIN OR HILL": "infomap_95_STONE OR ROCK",
  "GREEDY": "infomap_303_STINGY",
  "FLEA": "infomap_229_LOUSE",
  "LOOM": "infomap_72_WEAVE",
  "MARRIED WOMAN": "infomap_58_WIFE",
  "NORTH": "infomap_318_NORTH",
  "CHIN": "infomap_112_CHIN",
  "RING": "infomap_83_CIRCLE",
  "STEAL": "infomap_169_HIDE (CONCEAL)",
  "SELL": "infomap_89_SELL",
  "MILL": "infomap_226_MORTAR CRUSHER",
  "TAIL": "infomap_328_TAIL",
  "LOOK": "infomap_74_SEE",
  "EXPENSIVE": "infomap_126_EXPENSIVE",
  "FEEL": "infomap_5_UNDERSTAND",
  "PRECIOUS": "infomap_126_EXPENSIVE",
  "BELOW OR UNDER": "infomap_36_LOW",
  "EAR": "infomap_219_EAR",
  "WALK (TAKE A WALK)": "infomap_54_WALK",
  "RESCUE": "infomap_26_PRESERVE",
  "CHOP": "infomap_60_CUT",
  "SOMETIMES": "infomap_132_OFTEN",
  "NETBAG": "infomap_85_NETBAG",
  "CALCULATE": "infomap_23_COUNT",
  "MARE": "infomap_79_HORSE",
  "LIE (REST)": "infomap_134_SLEEP",
  "MARKET": "infomap_268_STORE",
  "HINDER": "infomap_194_DISTURB",
  "BREATH": "infomap_87_BREATHE",
  "WHICH": "infomap_65_WHAT",
  "THEIR": "infomap_22_THAT",
  "SLEEP (STATE)": "infomap_265_DREAM",
  "SKULL": "infomap_234_HEAD",
  "EARLOBE": "infomap_219_EAR",
  "CANOE": "infomap_80_CANOE",
  "YOLK": "infomap_50_YELLOW",
  "GOOD LUCK": "infomap_19_GRIEF",
  "JUDGMENT": "infomap_119_ADJUDICATE",
  "SWORD": "infomap_133_KNIFE",
  "LEATHER": "infomap_4_FUR",
  "NECKLACE": "infomap_207_NECKLACE",
  "ROOM": "infomap_56_HOUSE",
  "NIPPLE": "infomap_102_BREAST",
  "GATE": "infomap_239_DOOR",
  "FRESH": "infomap_221_FRESH",
  "BLUE": "infomap_97_GREEN",
  "SOUP": "infomap_31_WATER",
  "PAIN": "infomap_99_SICK",
  "BEVERAGE": "infomap_101_WINE",
  "BREAD": "infomap_236_FLOUR",
  "BITTER": "infomap_76_SALTY",
  "LEAD (CHEMICAL ELEMENT)": "infomap_211_TINPLATE",
  "BEAT": "infomap_43_CHIME (ACTION)",
  "PRISON": "infomap_123_PRISON",
  "FRUIT": "infomap_7_GRAIN",
  "OX": "infomap_57_CATTLE",
  "EASY": "infomap_215_EASY",
  "TRUTH": "infomap_6_CORRECT (RIGHT)",
  "PULL": "infomap_168_STRETCH",
  "BEAK": "infomap_44_BEAK",
  "SHOULDER": "infomap_237_SHOULDER",
  "VIOLENCE": "infomap_201_VIOLENCE",
  "SWARM (OF BIRDS)": "infomap_270_SWARM (OF BIRDS)",
  "BLACK": "infomap_27_DARKNESS",
  "FIRE": "infomap_130_FIRE",
  "SKIN (OF FRUIT)": "infomap_4_FUR"
};