var SUBG = {
  "FOG": "subgraph_309_SKY",
  "SWAMP": "subgraph_252_WORLD",
  "TURN AROUND": "subgraph_522_COME BACK",
  "CLOTH": "subgraph_773_CLOTHES",
  "ACHE": "subgraph_940_SICK",
  "DO": "subgraph_365_BUILD",
  "PART": "subgraph_397_FEW",
  "BUTTER": "subgraph_580_MEDICINE",
  "OINTMENT": "subgraph_816_FAT (ORGANIC SUBSTANCE)",
  "IF": "subgraph_1001_WHERE",
  "QUEEN": "subgraph_877_MASTER",
  "WORLD": "subgraph_36_EARTH (SOIL)",
  "SMELL (PERCEIVE)": "subgraph_437_HEAR",
  "ADJUDICATE": "subgraph_621_FAULT",
  "CARVE": "subgraph_539_CUT",
  "LOVE": "subgraph_456_WANT",
  "FLY (INSECT)": "subgraph_1032_MOSQUITO",
  "THATCH": "subgraph_373_LEAF",
  "THUNDER (VERB)": "subgraph_810_BRIGHT",
  "HIP": "subgraph_704_BUTTOCKS",
  "LIE (MISLEAD)": "subgraph_894_SELL",
  "TONGUE": "subgraph_634_SPEAK",
  "SKULL": "subgraph_933_HEAD",
  "CLIMB": "subgraph_464_RISE (MOVE UPWARDS)",
  "BOW": "subgraph_987_BOW",
  "SHUT": "subgraph_646_TIE",
  "DAUGHTER": "subgraph_34_CHILD (DESCENDANT)",
  "BREAD": "subgraph_784_DUST",
  "COLLARBONE": "subgraph_1057_SHOULDERBLADE",
  "TWINS": "subgraph_794_FEW",
  "PURSUE": "subgraph_535_CATCH",
  "FOLLOW": "subgraph_748_OBEY",
  "CURE": "subgraph_676_PRESERVE",
  "LIFE": "subgraph_204_SPIRIT",
  "LIMP": "subgraph_1082_LAME",
  "BONE": "subgraph_598_LEG",
  "HELMET": "subgraph_945_RAG",
  "AFTERNOON": "subgraph_304_DAY (NOT NIGHT)",
  "MUSIC": "subgraph_201_SAY",
  "JUMP": "subgraph_690_FLEE",
  "SCRAPE": "subgraph_484_DIG",
  "AUNT": "subgraph_99_MOTHER-IN-LAW (OF MAN)",
  "LETTER": "subgraph_531_LEAF",
  "FIRST": "subgraph_779_FACE",
  "COME": "subgraph_1_GET",
  "DINNER (SUPPER)": "subgraph_771_MEAL",
  "BLOW (WITH MOUTH)": "subgraph_952_BLOW (OF WIND)",
  "LUNCH": "subgraph_771_MEAL",
  "GENTLE": "subgraph_943_WEAK",
  "GRAIN": "subgraph_548_GRAIN",
  "GROUND": "subgraph_5_EARTH (SOIL)",
  "STORE": "subgraph_1066_STORE",
  "TASTE (SOMETHING)": "subgraph_408_HEAR",
  "NIECE": "subgraph_85_CHILD (DESCENDANT)",
  "WORM": "subgraph_962_ANIMAL",
  "RESCUE": "subgraph_579_DEFEND",
  "STRING": "subgraph_800_WAIST",
  "LOSE": "subgraph_620_DESTROY",
  "DONKEY": "subgraph_1016_HORSE",
  "FRIEND": "subgraph_367_RELATIVES",
  "WEATHER": "subgraph_114_WORLD",
  "GATE": "subgraph_900_PATH",
  "CATCH": "subgraph_49_GET",
  "BETRAY": "subgraph_894_SELL",
  "END (OF TIME)": "subgraph_221_END (OF SPACE)",
  "FOAL": "subgraph_1016_HORSE",
  "ATTACK": "subgraph_693_STRIKE OR BEAT",
  "RISE (MOVE UPWARDS)": "subgraph_80_RISE (MOVE UPWARDS)",
  "CUP": "subgraph_817_BOWL",
  "STRETCH": "subgraph_637_PULL",
  "EMBERS": "subgraph_376_FIRE",
  "BUTTOCKS": "subgraph_241_BOTTOM",
  "LIVER": "subgraph_606_SPIRIT",
  "CAR": "subgraph_1020_CAR",
  "HAPPEN": "subgraph_145_ARRIVE",
  "DIVE": "subgraph_997_SINK (DESCEND)",
  "FIND": "subgraph_82_GET",
  "SWORD": "subgraph_977_IRON",
  "EXTINGUISH": "subgraph_511_KILL",
  "COOK (SOMETHING)": "subgraph_173_COOK (SOMETHING)",
  "CAUSE TO (LET)": "subgraph_486_GIVE",
  "PREGNANT": "subgraph_774_HEAVY",
  "ARROW": "subgraph_826_BOW",
  "TOBACCO": "subgraph_590_DUST",
  "ARMY": "subgraph_1007_FIGHT",
  "LATE": "subgraph_130_DAY (NOT NIGHT)",
  "OLD WOMAN": "subgraph_412_GRANDMOTHER",
  "GATHER": "subgraph_13_TAKE",
  "DREAM": "subgraph_888_SLEEP",
  "PAIR": "subgraph_839_FEW",
  "BATTLE": "subgraph_570_KILL",
  "GOOD": "subgraph_166_CORRECT (RIGHT)",
  "GRANDFATHER": "subgraph_149_FATHER-IN-LAW (OF WOMAN)",
  "BUS": "subgraph_1020_CAR",
  "ANNOUNCE": "subgraph_157_SAY",
  "FINE (PENALTY)": "subgraph_1055_PUNISHMENT",
  "GRASS": "subgraph_278_TREE",
  "DIE": "subgraph_246_KILL",
  "LEATHER": "subgraph_491_FUR",
  "HOST": "subgraph_831_MASTER",
  "HANG UP": "subgraph_938_HEAVY",
  "BUDGE (ONESELF)": "subgraph_976_MOVE (ONESELF)",
  "LOUSE": "subgraph_1052_FLEA",
  "RAKE": "subgraph_1092_RAKE",
  "PEOPLE": "subgraph_8_COUNTRY",
  "BATTLE-AXE": "subgraph_1037_BATTLE-AXE",
  "GOURD": "subgraph_916_BOWL",
  "BRICK": "subgraph_1058_BRICK",
  "DECREASE": "subgraph_415_FALL",
  "SWARM (OF BIRDS)": "subgraph_1081_FLOCK (OF ANIMALS)",
  "WIDOWER": "subgraph_1079_WIDOW",
  "GREEDY": "subgraph_1062_GREEDY",
  "WAGES": "subgraph_631_PAY",
  "DEW": "subgraph_188_SKY",
  "PEACE": "subgraph_378_WORLD",
  "THRESH": "subgraph_385_STRIKE OR BEAT",
  "MOW": "subgraph_208_PICK UP",
  "ORNAMENT": "subgraph_860_PRECIPICE",
  "EARN": "subgraph_423_GET",
  "WARM": "subgraph_35_FIRE",
  "CLAY": "subgraph_69_EARTH (SOIL)",
  "BITE": "subgraph_611_DRINK",
  "STROKE (OF PEN)": "subgraph_836_THREAD",
  "HARD": "subgraph_416_BIG",
  "PAW": "subgraph_537_LEG",
  "CHANGE": "subgraph_528_BUY",
  "RYE": "subgraph_639_GRAIN",
  "RAIN (PRECIPITATION)": "subgraph_562_WATER",
  "MIDDAY": "subgraph_812_DINNER (SUPPER)",
  "PUBIC HAIR": "subgraph_407_FUR",
  "EAT": "subgraph_231_DRINK",
  "STATUE": "subgraph_1071_IDOL",
  "BREAST": "subgraph_799_HEART",
  "BOLT (OF LIGHTNING)": "subgraph_1024_THUNDER",
  "SIBLING'S CHILD": "subgraph_465_NEPHEW",
  "WHEN": "subgraph_786_HOW",
  "SCAR": "subgraph_897_WOUND",
  "PERSON": "subgraph_190_PEOPLE",
  "OTHER": "subgraph_1067_OTHER",
  "BED": "subgraph_960_BLANKET",
  "FRESH": "subgraph_937_AGAIN",
  "STEP (VERB)": "subgraph_527_LEAVE",
  "FIREPLACE": "subgraph_472_FIRE",
  "LEASH": "subgraph_1028_LEASH",
  "ARCH": "subgraph_885_BOW",
  "RESULT IN": "subgraph_131_ARRIVE",
  "LEAF (LEAFLIKE OBJECT)": "subgraph_834_LEAF",
  "LOW": "subgraph_134_BOTTOM",
  "ARRIVE": "subgraph_106_GET",
  "NAME": "subgraph_1000_CALL BY NAME",
  "DO OR MAKE": "subgraph_6_GIVE",
  "FISHHOOK": "subgraph_969_TRAP (PITFALL)",
  "HOW MANY": "subgraph_955_HOW",
  "BLOOD": "subgraph_568_EAT",
  "BROKEN": "subgraph_777_BREAK (DESTROY OR GET DESTROYED)",
  "UNTIE": "subgraph_913_LET GO OR SET FREE",
  "WHITE": "subgraph_510_YELLOW",
  "CHIEFTAIN": "subgraph_450_HEAD",
  "POINTED": "subgraph_345_END (OF SPACE)",
  "TORCH OR LAMP": "subgraph_311_FIRE",
  "BUILD": "subgraph_73_BUILD",
  "OBEY": "subgraph_186_HEAR",
  "CALF OF LEG": "subgraph_549_LEG",
  "CANOE": "subgraph_1021_BOAT",
  "FOOD": "subgraph_317_EAT",
  "TRAP (PITFALL)": "subgraph_722_TRAP (CATCH)",
  "SOME": "subgraph_380_FEW",
  "SHORT": "subgraph_326_SMALL",
  "MAT": "subgraph_754_COAT",
  "ELBOW": "subgraph_575_ARM",
  "AIR": "subgraph_155_TOP",
  "SKIN": "subgraph_270_FUR",
  "HOT": "subgraph_184_FIRE",
  "MOTHER-IN-LAW (OF WOMAN)": "subgraph_176_FATHER-IN-LAW (OF MAN)",
  "SMILE": "subgraph_1042_LAUGH",
  "WITH": "subgraph_862_INSIDE",
  "LEARN": "subgraph_172_KNOW (SOMETHING)",
  "GRANDMOTHER": "subgraph_124_MOTHER-IN-LAW (OF WOMAN)",
  "MIDDLE": "subgraph_929_HIP",
  "BAY": "subgraph_957_LAKE",
  "NEPHEW": "subgraph_115_NIECE",
  "PUNISHMENT": "subgraph_1055_PUNISHMENT",
  "SPACE (AVAILABLE)": "subgraph_288_EARTH (SOIL)",
  "SLICE": "subgraph_901_PART",
  "WHEEL": "subgraph_493_LEG",
  "CHIN": "subgraph_700_FACE",
  "BASKET": "subgraph_993_TRAP (PITFALL)",
  "FINGERNAIL OR TOENAIL": "subgraph_537_LEG",
  "PULL OFF (SKIN)": "subgraph_729_SKIN",
  "STAND UP": "subgraph_466_RISE (MOVE UPWARDS)",
  "KNIT": "subgraph_706_TIE",
  "DRIBBLE": "subgraph_181_FLOW",
  "GAP (DISTANCE)": "subgraph_540_PLACE (POSITION)",
  "PLANT (VEGETATION)": "subgraph_217_TREE",
  "CHIME (ACTION)": "subgraph_967_CHIME (ACTION)",
  "WHERE": "subgraph_742_HOW",
  "RED": "subgraph_647_YELLOW",
  "CROCODILE": "subgraph_1085_LIZARD",
  "SPLIT": "subgraph_322_CUT",
  "EASY": "subgraph_1029_LIGHT (WEIGHT)",
  "MARRIED MAN": "subgraph_601_HUSBAND",
  "THIN (SLIM)": "subgraph_609_SMALL",
  "WINDOW": "subgraph_939_DOOR",
  "WOMAN": "subgraph_384_DAUGHTER",
  "KISS": "subgraph_600_DRINK",
  "MACHINE": "subgraph_1020_CAR",
  "ANXIETY": "subgraph_920_GRIEF",
  "COOKHOUSE": "subgraph_555_FIRE",
  "LOWER ARM": "subgraph_745_ARM",
  "FEW": "subgraph_219_SMALL",
  "ASH": "subgraph_615_DUST",
  "AXE": "subgraph_1037_BATTLE-AXE",
  "THIGH": "subgraph_500_LEG",
  "SOUND (OF INSTRUMENT OR VOICE)": "subgraph_967_CHIME (ACTION)",
  "CHEW": "subgraph_611_DRINK",
  "BREAK (DESTROY OR GET DESTROYED)": "subgraph_463_BREAK (DESTROY OR GET DESTROYED)",
  "FLEA": "subgraph_1052_FLEA",
  "TURN": "subgraph_319_TWIST",
  "DIG": "subgraph_300_DIG",
  "BOARD": "subgraph_584_TREE",
  "MOUNTAIN OR HILL": "subgraph_452_TOP",
  "FAULT": "subgraph_856_FAULT",
  "RAM": "subgraph_1014_SHEEP",
  "SON": "subgraph_146_CHILD (DESCENDANT)",
  "SOLDIER": "subgraph_851_FIGHT",
  "WHISTLE": "subgraph_952_BLOW (OF WIND)",
  "FAITHFUL": "subgraph_563_CORRECT (RIGHT)",
  "ARSON": "subgraph_806_BURNING",
  "TEACH": "subgraph_386_SAY",
  "HOME": "subgraph_902_HOUSE",
  "SOW (FEMALE PIG)": "subgraph_1043_SOW (FEMALE PIG)",
  "VOICE": "subgraph_277_SPEAK",
  "SWEEP": "subgraph_736_SCRAPE",
  "PINCH": "subgraph_801_SQUEEZE",
  "MEDICINE": "subgraph_738_RESCUE",
  "NIGHT": "subgraph_390_LATE",
  "COIN": "subgraph_972_IRON",
  "MOON": "subgraph_927_SUN",
  "CLUB": "subgraph_171_FIRE",
  "STING": "subgraph_536_TREE",
  "BELIEVE": "subgraph_48_KNOW (SOMETHING)",
  "MURDER": "subgraph_644_KILL",
  "ANSWER": "subgraph_903_OBEY",
  "BANYAN": "subgraph_1073_BANYAN",
  "BOAR": "subgraph_1043_SOW (FEMALE PIG)",
  "AFTER": "subgraph_768_BEHIND",
  "THERE": "subgraph_966_THAT",
  "EVENING": "subgraph_482_LATE",
  "RETURN HOME": "subgraph_673_COME BACK",
  "MOUTH": "subgraph_132_EDGE",
  "WET": "subgraph_942_RAW",
  "YES": "subgraph_695_CORRECT (RIGHT)",
  "PUT": "subgraph_24_GIVE",
  "NEWS": "subgraph_1026_STORY",
  "BAG": "subgraph_1036_SACK",
  "TREE TRUNK": "subgraph_187_TREE",
  "STRENGTH": "subgraph_1035_STRENGTH",
  "COOKED": "subgraph_627_COOK (SOMETHING)",
  "FORBID": "subgraph_666_DEFEND",
  "LOOK": "subgraph_602_SEE",
  "FINISH": "subgraph_167_END (OF SPACE)",
  "REST": "subgraph_946_BREATHE",
  "BARK": "subgraph_232_FUR",
  "HATE": "subgraph_824_FIGHT",
  "JOIN": "subgraph_708_GATHER",
  "WIPE": "subgraph_871_SCRAPE",
  "BACK": "subgraph_441_BACK",
  "CAMPFIRE": "subgraph_664_FIRE",
  "DWELL (LIVE, RESIDE)": "subgraph_72_DWELL (LIVE, RESIDE)",
  "PRESIDENT": "subgraph_727_HEAD",
  "BEAUTIFUL": "subgraph_332_GOOD",
  "PRISONER": "subgraph_1027_SLAVE",
  "BIRD": "subgraph_841_ANIMAL",
  "MAN": "subgraph_140_PEOPLE",
  "SHIVER": "subgraph_1004_SHAKE",
  "PLATE": "subgraph_817_BOWL",
  "UPPER ARM": "subgraph_745_ARM",
  "IN": "subgraph_793_BOTTOM",
  "ANGER": "subgraph_992_FIGHT",
  "STOCKING": "subgraph_1039_SHOE",
  "COW": "subgraph_683_ANIMAL",
  "SHINE": "subgraph_312_LIGHT (RADIATION)",
  "MAINLAND": "subgraph_61_PLACE (POSITION)",
  "SEASON": "subgraph_424_DAY (NOT NIGHT)",
  "KNOT": "subgraph_706_TIE",
  "TEAR (SHRED)": "subgraph_206_CUT",
  "THUNDER": "subgraph_1024_THUNDER",
  "CLEAN (SOMETHING)": "subgraph_684_SCRAPE",
  "DIE (FROM ACCIDENT)": "subgraph_565_KILL",
  "HOPE": "subgraph_330_THINK (BELIEVE)",
  "THEY": "subgraph_893_HE",
  "TOUCH": "subgraph_29_CATCH",
  "IDEA": "subgraph_343_SPIRIT",
  "YESTERDAY": "subgraph_759_EARLY",
  "PUT ON": "subgraph_342_PUT",
  "PRESS": "subgraph_617_SQUEEZE",
  "GLASS": "subgraph_939_DOOR",
  "UPPER BACK": "subgraph_83_BEHIND",
  "PARENTS-IN-LAW": "subgraph_557_FATHER-IN-LAW (OF MAN)",
  "MARE": "subgraph_1016_HORSE",
  "HOW MUCH": "subgraph_891_HOW",
  "COLOR": "subgraph_730_SCRAPE",
  "END (OF SPACE)": "subgraph_38_END (OF SPACE)",
  "HERE": "subgraph_910_THAT",
  "BORROW": "subgraph_52_GET",
  "SMALL": "subgraph_43_SMALL",
  "SALTY": "subgraph_560_SWEET",
  "SWING (SOMETHING)": "subgraph_899_SHAKE",
  "MARRIED WOMAN": "subgraph_726_WOMAN",
  "GO UP (ASCEND)": "subgraph_195_RISE (MOVE UPWARDS)",
  "BOTTLE": "subgraph_892_DOOR",
  "MEAT": "subgraph_569_FOOD",
  "FRONT TOOTH (INCISOR)": "subgraph_953_BEAK",
  "GRIEF": "subgraph_702_PAIN",
  "CIGARETTE": "subgraph_956_SMOKE (EXHAUST)",
  "FLESH": "subgraph_577_BODY",
  "HINDER": "subgraph_1045_DISTURB",
  "SHELL": "subgraph_491_FUR",
  "PIERCE": "subgraph_886_PLAIT OR BRAID OR WEAVE",
  "CRAWL": "subgraph_567_RISE (MOVE UPWARDS)",
  "HORSE": "subgraph_1016_HORSE",
  "PADLOCK": "subgraph_1023_LATCH",
  "FISH TRAP": "subgraph_321_TRAP (CATCH)",
  "VILLAGE": "subgraph_148_COUNTRY",
  "CORRECT (RIGHT)": "subgraph_283_CORRECT (RIGHT)",
  "DISEASE": "subgraph_752_PAIN",
  "PAY": "subgraph_3_GIVE",
  "STEAL": "subgraph_1003_BURY",
  "EARLY": "subgraph_509_EARLY",
  "SOUND OR NOISE": "subgraph_740_VOICE",
  "ROT": "subgraph_1072_ROT",
  "FOOT": "subgraph_329_LEG",
  "PRICE": "subgraph_669_PAY",
  "NAIL (TOOL)": "subgraph_514_FOOT",
  "HEADBAND": "subgraph_689_CLOTH",
  "POT": "subgraph_817_BOWL",
  "WORK (ACTIVITY)": "subgraph_717_BUILD",
  "TENT": "subgraph_687_HOUSE",
  "TALK": "subgraph_547_SPEAK",
  "THEN": "subgraph_778_LATE",
  "HEN": "subgraph_746_ANIMAL",
  "LIGHT (RADIATION)": "subgraph_79_LIGHT (RADIATION)",
  "BELT": "subgraph_1028_LEASH",
  "BEESWAX": "subgraph_613_FIRE",
  "CHILI PEPPER": "subgraph_1056_PEPPER",
  "SMELL (STINK)": "subgraph_421_HEAR",
  "BESIDE": "subgraph_692_SIDE",
  "CULTIVATE": "subgraph_508_SOW SEEDS",
  "MOLAR TOOTH": "subgraph_701_NOSE",
  "ADOBE": "subgraph_1058_BRICK",
  "GRANDPARENTS": "subgraph_488_FATHER-IN-LAW (OF WOMAN)",
  "TOOTH": "subgraph_787_BEAK",
  "CART": "subgraph_1020_CAR",
  "POUCH": "subgraph_1036_SACK",
  "SOW SEEDS": "subgraph_227_PLANT (VEGETATION)",
  "PESTLE": "subgraph_682_GRIND",
  "COAST": "subgraph_855_SHORE",
  "PAINTING": "subgraph_1018_PAINTING",
  "GRANDCHILD": "subgraph_734_GRANDMOTHER",
  "PALM OF HAND": "subgraph_410_GIVE",
  "STRAP": "subgraph_1028_LEASH",
  "PILE UP": "subgraph_608_GATHER",
  "SINK (DESCEND)": "subgraph_705_SINK (DESCEND)",
  "BRING": "subgraph_22_CARRY",
  "FENCE": "subgraph_782_WALL (OF HOUSE)",
  "PRECIOUS": "subgraph_391_PAY",
  "TOWN": "subgraph_371_COUNTRY",
  "INTESTINES": "subgraph_361_SPIRIT",
  "CARRY ON SHOULDER": "subgraph_215_TAKE",
  "CONCEIVE": "subgraph_372_THINK (BELIEVE)",
  "SPEAK": "subgraph_7_SAY",
  "SEPARATE": "subgraph_41_LEAVE",
  "SLAB": "subgraph_355_TREE",
  "STREAM (FLOW CONTINUOUSLY)": "subgraph_790_FLOW",
  "BURN (SOMETHING)": "subgraph_168_COOK (SOMETHING)",
  "BEND": "subgraph_515_TWIST",
  "LUNG": "subgraph_606_SPIRIT",
  "HURRY": "subgraph_928_EARLY",
  "CURSE": "subgraph_968_FIGHT",
  "WING": "subgraph_216_FEATHER",
  "HALF": "subgraph_633_SIDE",
  "MAST": "subgraph_781_POST",
  "VAGINA": "subgraph_1089_VAGINA",
  "DREAM (SOMETHING)": "subgraph_888_SLEEP",
  "SON-IN-LAW (OF MAN)": "subgraph_90_MOTHER-IN-LAW (OF WOMAN)",
  "POSTCARD": "subgraph_382_LEAF",
  "THICK": "subgraph_400_BIG",
  "COLD (CHILL)": "subgraph_971_COLD",
  "MEET": "subgraph_129_GET",
  "SING": "subgraph_65_SAY",
  "PAINT (PIGMENTS)": "subgraph_1018_PAINTING",
  "KETTLE": "subgraph_880_BOWL",
  "GROW": "subgraph_37_RISE (MOVE UPWARDS)",
  "MESSAGE": "subgraph_1026_STORY",
  "BOTHER (HARASS)": "subgraph_1045_DISTURB",
  "HELL": "subgraph_664_FIRE",
  "GRAVE": "subgraph_760_HOLE",
  "ENTER": "subgraph_75_PUT",
  "BODY": "subgraph_180_SKIN",
  "PUS": "subgraph_504_DIE",
  "PUSH": "subgraph_375_TREE",
  "POUND": "subgraph_546_STRIKE OR BEAT",
  "TOWEL": "subgraph_1005_CLOTH",
  "ROCK": "subgraph_445_HEAD",
  "DIVORCE": "subgraph_331_LEAVE",
  "FIELD": "subgraph_174_EARTH (SOIL)",
  "CERTAIN": "subgraph_695_CORRECT (RIGHT)",
  "KNIFE": "subgraph_977_IRON",
  "GUARD": "subgraph_444_KEEP",
  "UGLY": "subgraph_699_DIRTY",
  "BOUNDARY": "subgraph_229_END (OF SPACE)",
  "FEATHER": "subgraph_202_FUR",
  "WHISPER": "subgraph_1090_WHISPER",
  "CLEVER": "subgraph_1091_CLEVER",
  "FOR A LONG TIME": "subgraph_988_LONG",
  "SWELLING": "subgraph_640_INJURE",
  "FRINGE": "subgraph_185_END (OF SPACE)",
  "CHOKE": "subgraph_954_SINK (DESCEND)",
  "CARRY IN HAND": "subgraph_107_TAKE",
  "CHANGE (BECOME DIFFERENT)": "subgraph_347_BUY",
  "SWIM": "subgraph_649_FLOW",
  "GOD": "subgraph_393_SKY",
  "MELT": "subgraph_1053_MELT",
  "PLANT (SOMETHING)": "subgraph_84_RISE (MOVE UPWARDS)",
  "HALT (STOP)": "subgraph_334_DUST",
  "MUD": "subgraph_18_EARTH (SOIL)",
  "FUR": "subgraph_298_FUR",
  "STREET": "subgraph_822_PATH",
  "SNIFF": "subgraph_592_HEAR",
  "PEEL": "subgraph_470_SKIN",
  "SCALE": "subgraph_909_BARK",
  "CEASE": "subgraph_160_DUST",
  "ROW": "subgraph_850_MIX",
  "BE LATE": "subgraph_589_LATE",
  "CLOTHES": "subgraph_618_CLOTHES",
  "SPIRIT": "subgraph_91_SPIRIT",
  "WELL": "subgraph_1084_SPRING (OF WATER)",
  "HEAD": "subgraph_26_END (OF SPACE)",
  "TALL": "subgraph_220_BIG",
  "SLOW": "subgraph_480_LATE",
  "DAY (NOT NIGHT)": "subgraph_33_LIGHT (RADIATION)",
  "LOUD": "subgraph_349_BIG",
  "ANIMAL": "subgraph_571_ANIMAL",
  "NATIVE COUNTRY": "subgraph_457_COUNTRY",
  "FAIRY TALE": "subgraph_1026_STORY",
  "CLAN": "subgraph_141_CHILD (DESCENDANT)",
  "VULTURE": "subgraph_1041_VULTURE",
  "SIBLING": "subgraph_273_COUSIN",
  "POWERFUL": "subgraph_1002_STRONG",
  "UNRIPE": "subgraph_350_YOUNG",
  "EARLOBE": "subgraph_731_HEAR",
  "CROWD": "subgraph_481_PEOPLE",
  "SHOOT": "subgraph_70_KILL",
  "CHILD (DESCENDANT)": "subgraph_67_CHILD (DESCENDANT)",
  "ROOM": "subgraph_325_PLACE (POSITION)",
  "IT": "subgraph_890_THAT",
  "DENY": "subgraph_964_FORBID",
  "RETREAT": "subgraph_413_LEAVE",
  "BE SILENT": "subgraph_975_QUIET",
  "SICK": "subgraph_688_PAIN",
  "FEEL": "subgraph_98_KNOW (SOMETHING)",
  "SHIP": "subgraph_1021_BOAT",
  "SPOIL (BECOME SPOILED)": "subgraph_1072_ROT",
  "GREY": "subgraph_941_BLUE",
  "BRIGHT": "subgraph_337_LIGHT (RADIATION)",
  "FLOUR": "subgraph_553_DUST",
  "EGG": "subgraph_471_SEED",
  "PIG": "subgraph_1043_SOW (FEMALE PIG)",
  "HORN (ANATOMY)": "subgraph_924_BRANCH",
  "BLOOD VESSEL": "subgraph_302_BOTTOM",
  "MOUSTACHE": "subgraph_700_FACE",
  "YARD": "subgraph_842_FENCE",
  "REGRET": "subgraph_815_GRIEF",
  "PRAY": "subgraph_694_ASK (REQUEST)",
  "SHOW": "subgraph_194_SAY",
  "DANCE": "subgraph_561_SING",
  "MUMBLE": "subgraph_1090_WHISPER",
  "SHAKE": "subgraph_680_SHAKE",
  "DEATH": "subgraph_565_KILL",
  "GAME": "subgraph_853_JUMP",
  "NOTICE (SOMETHING)": "subgraph_868_SEE",
  "SNOW": "subgraph_1069_ICE",
  "PIECE": "subgraph_901_PART",
  "WATCH": "subgraph_643_SEE",
  "BOAST": "subgraph_670_ASK (REQUEST)",
  "SEEM": "subgraph_293_THINK (BELIEVE)",
  "GHOST": "subgraph_313_SPIRIT",
  "SOON": "subgraph_578_EARLY",
  "GLUE": "subgraph_884_WATER",
  "SQUEEZE": "subgraph_205_TWIST",
  "SINK (DISAPPEAR IN WATER)": "subgraph_930_SINK (DESCEND)",
  "PENIS": "subgraph_471_SEED",
  "WOMB": "subgraph_361_SPIRIT",
  "LAUGH": "subgraph_1042_LAUGH",
  "WASP": "subgraph_741_HONEY",
  "LADDER": "subgraph_1077_BRIDGE",
  "LENGTH": "subgraph_988_LONG",
  "CLEAR": "subgraph_388_LIGHT (RADIATION)",
  "HUT": "subgraph_755_HOUSE",
  "WEAVE": "subgraph_234_TWIST",
  "GROAN": "subgraph_691_SING",
  "WIDE": "subgraph_285_BIG",
  "SCOLD": "subgraph_968_FIGHT",
  "CROUCH": "subgraph_766_SIT",
  "AMOUNT": "subgraph_1074_AMOUNT",
  "PROUD": "subgraph_670_ASK (REQUEST)",
  "REMAIN": "subgraph_14_DUST",
  "CLOCK": "subgraph_656_TIME",
  "THIN (OF SHAPE OF OBJECT)": "subgraph_175_SMALL",
  "OATH": "subgraph_247_SAY",
  "ROPE": "subgraph_980_LINE",
  "ONLY": "subgraph_420_FEW",
  "DRAG": "subgraph_645_TEAR (SHRED)",
  "GRAPE": "subgraph_875_LINE",
  "STRIKE OR BEAT": "subgraph_162_KILL",
  "SHOULDER": "subgraph_396_ARM",
  "DESCENDANTS": "subgraph_686_CHILD (YOUNG HUMAN)",
  "HAIR": "subgraph_189_FUR",
  "LIE DOWN": "subgraph_505_DWELL (LIVE, RESIDE)",
  "DANGER": "subgraph_389_THINK (BELIEVE)",
  "CONNECT": "subgraph_521_TIE",
  "CAPE": "subgraph_665_BEAK",
  "EXPLAIN": "subgraph_163_SAY",
  "MOTHER'S SISTER": "subgraph_370_MOTHER-IN-LAW (OF WOMAN)",
  "LEND": "subgraph_291_GIVE",
  "PRESERVE": "subgraph_165_HOLD",
  "BOAT": "subgraph_1021_BOAT",
  "BOIL (OF LIQUID)": "subgraph_792_COOK (SOMETHING)",
  "FATHER'S SISTER": "subgraph_328_MOTHER-IN-LAW (OF WOMAN)",
  "SEA": "subgraph_501_RIVER",
  "BEGIN": "subgraph_525_FACE",
  "MISTAKE": "subgraph_950_FAULT",
  "HEART": "subgraph_251_SPIRIT",
  "INVITE": "subgraph_498_ASK (REQUEST)",
  "FEMALE (OF ANIMAL)": "subgraph_677_WOMAN",
  "BLIND": "subgraph_1051_BLIND",
  "COAT": "subgraph_876_CLOTHES",
  "UDDER": "subgraph_728_HEART",
  "BEAT": "subgraph_663_KILL",
  "DRY": "subgraph_995_QUIET",
  "LONG HAIR": "subgraph_973_FUR",
  "NORTH": "subgraph_1063_SOUTH",
  "STRAIGHT": "subgraph_454_CORRECT (RIGHT)",
  "BILL": "subgraph_494_COUNT",
  "BLUE": "subgraph_439_YELLOW",
  "FIREWOOD": "subgraph_249_FIRE",
  "VEIN": "subgraph_266_BOTTOM",
  "JAGUAR": "subgraph_1030_JAGUAR",
  "FURROW": "subgraph_949_HOLE",
  "ENOUGH": "subgraph_982_MANY",
  "JEWEL": "subgraph_723_WALL (OF HOUSE)",
  "DRIP (EMIT LIQUID)": "subgraph_406_FLOW",
  "DONATE": "subgraph_486_GIVE",
  "LIVESTOCK": "subgraph_896_ANIMAL",
  "STREAM": "subgraph_650_DRINK",
  "FLOW": "subgraph_50_LEAVE",
  "PREVENT": "subgraph_804_DEFEND",
  "HOE": "subgraph_847_ROW",
  "FAMINE": "subgraph_1040_HUNGER",
  "OCEAN": "subgraph_791_LAKE",
  "STATE (POLITICS)": "subgraph_564_COUNTRY",
  "OLD": "subgraph_286_BIG",
  "SHIRT": "subgraph_714_CLOTHES",
  "AUTUMN": "subgraph_780_YEAR",
  "THAW (DEW)": "subgraph_1053_MELT",
  "PERMIT": "subgraph_138_GIVE",
  "PITCHFORK": "subgraph_551_BRANCH",
  "MAIZE": "subgraph_639_GRAIN",
  "UP": "subgraph_222_TOP",
  "ROLL": "subgraph_272_TWIST",
  "NEEDLE TREE": "subgraph_758_NAIL (TOOL)",
  "CENTIPEDE": "subgraph_1086_CENTIPEDE",
  "WALK": "subgraph_31_LEAVE",
  "WHICH": "subgraph_744_WHAT",
  "ROUND": "subgraph_749_FOOT",
  "PRODUCE": "subgraph_365_BUILD",
  "TINKLE": "subgraph_931_CHIME (ACTION)",
  "BOLT (MOVE IN HASTE)": "subgraph_835_EARLY",
  "MEASURE": "subgraph_303_FEEL",
  "POST": "subgraph_402_TREE",
  "MALE": "subgraph_401_HUSBAND",
  "KEEP": "subgraph_58_KEEP",
  "OPEN": "subgraph_913_LET GO OR SET FREE",
  "DOG": "subgraph_1030_JAGUAR",
  "TOMORROW": "subgraph_881_EARLY",
  "FLUTE": "subgraph_845_BRANCH",
  "GET": "subgraph_94_GET",
  "DUST": "subgraph_105_EARTH (SOIL)",
  "TURTLE": "subgraph_1093_TURTLE",
  "LICK": "subgraph_807_DRINK",
  "THINK (BELIEVE)": "subgraph_42_KNOW (SOMETHING)",
  "EVIL": "subgraph_767_BAD",
  "TWINKLE": "subgraph_974_LIGHT (RADIATION)",
  "LEAF": "subgraph_142_FEATHER",
  "NECKLACE": "subgraph_878_NECK",
  "ARMOUR": "subgraph_1064_ARMOUR",
  "STICK": "subgraph_182_TREE",
  "WRITE": "subgraph_453_FUR",
  "FAT (ORGANIC SUBSTANCE)": "subgraph_427_MEDICINE",
  "CALL": "subgraph_314_ASK (REQUEST)",
  "BAKE": "subgraph_203_COOK (SOMETHING)",
  "SHOVEL": "subgraph_847_ROW",
  "CHICKEN": "subgraph_746_ANIMAL",
  "DYE": "subgraph_1018_PAINTING",
  "PASTURE": "subgraph_461_PLANT (VEGETATION)",
  "WE": "subgraph_1022_WE (EXCLUSIVE)",
  "SACK": "subgraph_1036_SACK",
  "MONEY": "subgraph_972_IRON",
  "SMOKE (EXHAUST)": "subgraph_284_DUST",
  "TESTICLES": "subgraph_813_SEED",
  "STOVE": "subgraph_472_FIRE",
  "KING": "subgraph_715_MASTER",
  "BOIL (SOMETHING)": "subgraph_340_PUT",
  "BEE": "subgraph_959_HONEY",
  "BODY LOUSE": "subgraph_1070_HEAD LOUSE",
  "VALLEY": "subgraph_753_FLAT",
  "MASTER": "subgraph_126_FATHER",
  "CANDLE": "subgraph_311_FIRE",
  "WAVE": "subgraph_1076_WAVE",
  "HEAR": "subgraph_11_UNDERSTAND",
  "SAP": "subgraph_636_DRINK",
  "ROOSTER": "subgraph_746_ANIMAL",
  "LAMB": "subgraph_1014_SHEEP",
  "LIBERATE": "subgraph_915_LET GO OR SET FREE",
  "COME BACK": "subgraph_23_GET",
  "DEMON": "subgraph_267_SPIRIT",
  "THIS": "subgraph_867_THAT",
  "NOT": "subgraph_869_FORBID",
  "RAINBOW": "subgraph_885_BOW",
  "MAGIC": "subgraph_1034_MAGICIAN",
  "DISTURB": "subgraph_1045_DISTURB",
  "MAGICIAN": "subgraph_1034_MAGICIAN",
  "CUSTOM": "subgraph_499_SEEM",
  "PAIN": "subgraph_290_PAIN",
  "STOMACH": "subgraph_469_SPIRIT",
  "PASS": "subgraph_436_ARRIVE",
  "PUMPKIN": "subgraph_916_BOWL",
  "CHEAP": "subgraph_1029_LIGHT (WEIGHT)",
  "GIVE": "subgraph_10_TAKE",
  "IMMEDIATELY": "subgraph_578_EARLY",
  "ROAD": "subgraph_635_PATH",
  "HOLE": "subgraph_970_HOLE",
  "FALL": "subgraph_348_FALL",
  "GUN": "subgraph_979_BOW",
  "FISH": "subgraph_820_FOOD",
  "KID": "subgraph_1014_SHEEP",
  "LAZY": "subgraph_943_WEAK",
  "FACE": "subgraph_430_FACE",
  "NEW": "subgraph_520_YOUNG",
  "RIGHT": "subgraph_529_CORRECT (RIGHT)",
  "CRY": "subgraph_691_SING",
  "TEMPLE": "subgraph_1044_TEMPLE",
  "CHILD (YOUNG HUMAN)": "subgraph_121_CHILD (DESCENDANT)",
  "TREE STUMP": "subgraph_433_TREE",
  "RIDGEPOLE": "subgraph_552_POST",
  "FRY": "subgraph_792_COOK (SOMETHING)",
  "RAZOR": "subgraph_681_IRON",
  "BORE": "subgraph_963_STAB",
  "SWEET POTATO": "subgraph_1031_YAM",
  "HOOK": "subgraph_969_TRAP (PITFALL)",
  "DOWN OR BELOW": "subgraph_451_BOTTOM",
  "DIVIDE": "subgraph_275_GIVE",
  "CHAT (WITH SOMEBODY)": "subgraph_625_SPEAK",
  "LAME": "subgraph_1082_LAME",
  "PATH OR ROAD": "subgraph_718_PATH",
  "POOR": "subgraph_1038_POOR",
  "PITY": "subgraph_698_WANT",
  "FOREHEAD": "subgraph_225_MOUTH",
  "SHORE": "subgraph_39_RISE (MOVE UPWARDS)",
  "INSTANTLY": "subgraph_819_IMMEDIATELY",
  "ALONE": "subgraph_420_FEW",
  "LET GO OR SET FREE": "subgraph_226_LET GO OR SET FREE",
  "TOE": "subgraph_449_LEG",
  "SEVERE": "subgraph_767_BAD",
  "OWE": "subgraph_487_COUNT",
  "VICTORY": "subgraph_1048_VICTORY",
  "VISIBLE": "subgraph_739_EXPLAIN",
  "LAND": "subgraph_60_PLACE (POSITION)",
  "MARKET": "subgraph_1066_STORE",
  "SAME": "subgraph_648_SEEM",
  "NEVER": "subgraph_811_MANY",
  "WALL (OF HOUSE)": "subgraph_475_SIDE",
  "TIRED": "subgraph_943_WEAK",
  "JUG": "subgraph_880_BOWL",
  "CHURCH": "subgraph_1044_TEMPLE",
  "CLEAN": "subgraph_479_CLEAN",
  "LEAVE": "subgraph_95_LEAVE",
  "LOCK": "subgraph_1023_LATCH",
  "WORD": "subgraph_71_SAY",
  "APPROACH": "subgraph_398_COME BACK",
  "HOLLOW OUT": "subgraph_735_DIG",
  "NEEDLE (FOR SEWING)": "subgraph_1019_NEEDLE (FOR SEWING)",
  "FINE OR THIN": "subgraph_609_SMALL",
  "PEG": "subgraph_514_FOOT",
  "SIMILAR": "subgraph_751_SEEM",
  "LINE": "subgraph_980_LINE",
  "DOUGH": "subgraph_784_DUST",
  "SKIRT": "subgraph_1011_CLOTHES",
  "WHITHER (WHERE TO)": "subgraph_996_HOW",
  "CHOP": "subgraph_193_CUT",
  "LANGUAGE": "subgraph_103_SAY",
  "BACKWARD": "subgraph_1083_BACK (DIRECTION)",
  "OLD (AGED)": "subgraph_750_OLD",
  "SCORPION": "subgraph_1086_CENTIPEDE",
  "MILL": "subgraph_990_GRIND",
  "EXPENSIVE": "subgraph_864_EXPENSIVE",
  "HELP": "subgraph_320_PRESERVE",
  "GREEN": "subgraph_439_YELLOW",
  "BRIDGE": "subgraph_1077_BRIDGE",
  "BREAKFAST": "subgraph_318_EAT",
  "DAMP": "subgraph_942_RAW",
  "SEND": "subgraph_258_DRIVE",
  "CATTLE": "subgraph_843_ANIMAL",
  "MEETING HOUSE": "subgraph_1044_TEMPLE",
  "BERRY": "subgraph_639_GRAIN",
  "DRAW MILK": "subgraph_849_GRIND",
  "THOUGHT": "subgraph_523_SPIRIT",
  "SWING (MOVEMENT)": "subgraph_818_SHAKE",
  "FINGER": "subgraph_658_HAND",
  "YEAR": "subgraph_379_COLD",
  "HANG": "subgraph_756_HEAVY",
  "ALL": "subgraph_982_MANY",
  "WALKING STICK": "subgraph_654_TREE",
  "WIND": "subgraph_308_BLOW (OF WIND)",
  "WEAPONS": "subgraph_979_BOW",
  "LIE (REST)": "subgraph_888_SLEEP",
  "ROAST OR FRY": "subgraph_253_COOK (SOMETHING)",
  "FLAME": "subgraph_664_FIRE",
  "YOUNGER BROTHER": "subgraph_262_COUSIN",
  "GO": "subgraph_54_LEAVE",
  "CHAIN": "subgraph_878_NECK",
  "EARTH (SOIL)": "subgraph_119_EARTH (SOIL)",
  "STABLE": "subgraph_641_WALL (OF HOUSE)",
  "SEE": "subgraph_15_GET",
  "ORPHAN": "subgraph_1038_POOR",
  "DRESS": "subgraph_858_CLOTHES",
  "STEPSON": "subgraph_1047_STEPDAUGHTER",
  "YOUNG WOMAN": "subgraph_306_CHILD (YOUNG HUMAN)",
  "ONCE (IN THE PAST)": "subgraph_1088_ONCE (IN THE PAST)",
  "DOOR": "subgraph_543_MOUTH",
  "LAKE": "subgraph_265_RIVER",
  "SPADE": "subgraph_850_MIX",
  "LIGHT (COLOR)": "subgraph_337_LIGHT (RADIATION)",
  "GRIND": "subgraph_591_GRIND",
  "THITHER (THERE TO)": "subgraph_966_THAT",
  "WANT": "subgraph_280_ASK (REQUEST)",
  "RABBIT": "subgraph_1049_RABBIT",
  "CAST": "subgraph_586_FLOW",
  "DAWN": "subgraph_263_LIGHT (RADIATION)",
  "HE OR SHE OR IT": "subgraph_783_THAT",
  "RINSE": "subgraph_986_SWIM",
  "STAB": "subgraph_405_STAB",
  "WORSHIP": "subgraph_670_ASK (REQUEST)",
  "BE": "subgraph_315_CARRY IN HAND",
  "DOUBT": "subgraph_153_KNOW (SOMETHING)",
  "AND": "subgraph_1013_AGAIN",
  "BEEHIVE": "subgraph_741_HONEY",
  "BATHE": "subgraph_544_FLOW",
  "SHARP": "subgraph_605_END (OF SPACE)",
  "MEAD": "subgraph_958_WINE",
  "SMOKE (INHALE)": "subgraph_344_DRINK",
  "ZERO": "subgraph_297_HIDE (CONCEAL)",
  "QUARREL": "subgraph_593_KILL",
  "NEED (NOUN)": "subgraph_907_WANT",
  "FULL": "subgraph_336_BIG",
  "PROMISE": "subgraph_364_SAY",
  "BEFORE": "subgraph_671_EARLY",
  "BROOM": "subgraph_1092_RAKE",
  "CORPSE": "subgraph_230_SPIRIT",
  "BREATHE": "subgraph_200_SPIRIT",
  "YOUNGER SISTER": "subgraph_159_COUSIN",
  "STORM": "subgraph_805_BLOW (OF WIND)",
  "SEW": "subgraph_612_WEAVE",
  "LIFT": "subgraph_2_TAKE",
  "PLAIT": "subgraph_534_TWIST",
  "ROTTEN": "subgraph_582_DIE",
  "SONG": "subgraph_360_SAY",
  "NOW": "subgraph_747_IMMEDIATELY",
  "STAND": "subgraph_238_RISE (MOVE UPWARDS)",
  "THOU": "subgraph_893_HE",
  "HEADGEAR": "subgraph_689_CLOTH",
  "BROTHER": "subgraph_136_COUSIN",
  "LIKE": "subgraph_764_WANT",
  "CONVERSATION": "subgraph_679_SPEAK",
  "LAND (DESCEND)": "subgraph_387_ARRIVE",
  "SAIL": "subgraph_725_FLOW",
  "BAIT": "subgraph_820_FOOD",
  "MAKE": "subgraph_365_BUILD",
  "FATHER-IN-LAW (OF MAN)": "subgraph_4_FATHER-IN-LAW (OF MAN)",
  "I": "subgraph_1022_WE (EXCLUSIVE)",
  "OFTEN": "subgraph_837_MANY",
  "SURPRISED": "subgraph_923_GRIEF",
  "FORGET": "subgraph_737_DESTROY",
  "WEAK": "subgraph_603_THIN (OF SHAPE OF OBJECT)",
  "HIDE (CONCEAL)": "subgraph_237_KEEP",
  "STEPDAUGHTER": "subgraph_1047_STEPDAUGHTER",
  "DEAF": "subgraph_1025_MUTE",
  "COLD": "subgraph_431_COLD",
  "NASAL MUCUS (SNOT)": "subgraph_242_COLD",
  "BECOME": "subgraph_506_BE BORN",
  "SWEAR": "subgraph_495_SAY",
  "WEDDING": "subgraph_483_SLEEP",
  "HILL": "subgraph_1017_MOUNTAIN",
  "HOLY": "subgraph_934_CLEAN",
  "POUR": "subgraph_212_LEAVE",
  "SPOIL (SOMEBODY OR SOMETHING)": "subgraph_866_DESTROY",
  "DARE": "subgraph_904_STRONG",
  "TINPLATE": "subgraph_961_IRON",
  "THINK (REFLECT)": "subgraph_158_THINK (BELIEVE)",
  "YOUNG MAN": "subgraph_306_CHILD (YOUNG HUMAN)",
  "CONVICT": "subgraph_697_BLAME",
  "SET (HEAVENLY BODIES)": "subgraph_919_PUT ON",
  "YOLK": "subgraph_776_YELLOW",
  "LIGHT (IGNITE)": "subgraph_585_BURNING",
  "SHE": "subgraph_925_THAT",
  "FAMILY": "subgraph_305_RELATIVES",
  "WHAT": "subgraph_668_WHAT",
  "STALLION": "subgraph_1016_HORSE",
  "LIZARD": "subgraph_1085_LIZARD",
  "LAIR": "subgraph_994_HOLE",
  "RAW": "subgraph_467_BE ALIVE",
  "INTENTION": "subgraph_513_MIND",
  "RUN": "subgraph_496_FLOW",
  "CHOOSE": "subgraph_135_TAKE",
  "BRAIN": "subgraph_523_SPIRIT",
  "SPINE": "subgraph_827_BACK",
  "HEAVY": "subgraph_642_HEAVY",
  "MOSQUITO": "subgraph_1032_MOSQUITO",
  "HIGH TIDE": "subgraph_1060_HIGH TIDE",
  "CHAIR": "subgraph_177_EARTH (SOIL)",
  "LIGHT (WEIGHT)": "subgraph_1029_LIGHT (WEIGHT)",
  "JOY": "subgraph_1075_JOY",
  "KEY": "subgraph_1023_LATCH",
  "OUTRIGGER": "subgraph_1021_BOAT",
  "FORMER": "subgraph_750_OLD",
  "HOW": "subgraph_733_WHAT",
  "HEAT": "subgraph_789_SICK",
  "LIGHTNING": "subgraph_1024_THUNDER",
  "GRANDSON": "subgraph_209_NEPHEW",
  "CLAW": "subgraph_762_CLAW",
  "PUMA": "subgraph_1030_JAGUAR",
  "CARRY UNDER ARM": "subgraph_279_TAKE",
  "CHILD-IN-LAW": "subgraph_530_MOTHER-IN-LAW (OF WOMAN)",
  "BEARD": "subgraph_700_FACE",
  "ADMIT": "subgraph_111_KNOW (SOMETHING)",
  "SUNDAY": "subgraph_1065_SUNDAY",
  "PERJURY": "subgraph_894_SELL",
  "FIRE": "subgraph_96_FIRE",
  "MEAL": "subgraph_532_EAT",
  "CUT": "subgraph_245_CUT",
  "ASK (INQUIRE)": "subgraph_128_HEAR",
  "SKIN (OF FRUIT)": "subgraph_572_FUR",
  "POWER": "subgraph_1035_STRENGTH",
  "DISAPPEAR": "subgraph_503_DIE",
  "DEAR": "subgraph_712_DIFFICULT",
  "KNOW (SOMETHING)": "subgraph_68_KNOW (SOMETHING)",
  "COUNT": "subgraph_19_COUNT",
  "SCRATCH": "subgraph_261_DIG",
  "HAIR (HEAD)": "subgraph_566_FUR",
  "BARLEY": "subgraph_639_GRAIN",
  "MIX": "subgraph_490_SHAKE",
  "GOOD-LOOKING": "subgraph_1006_BEAUTIFUL",
  "BEVERAGE": "subgraph_223_RIVER",
  "DECEIT": "subgraph_894_SELL",
  "LAW": "subgraph_499_SEEM",
  "PADDLE": "subgraph_850_MIX",
  "RUG": "subgraph_873_BLANKET",
  "PLACE (POSITION)": "subgraph_87_EARTH (SOIL)",
  "YELLOW": "subgraph_417_YELLOW",
  "BE BORN": "subgraph_127_BE ALIVE",
  "SAUSAGE": "subgraph_361_SPIRIT",
  "MISS (A TARGET)": "subgraph_950_FAULT",
  "POISON": "subgraph_674_RESCUE",
  "BOWL": "subgraph_772_BOWL",
  "MOTHER'S BROTHER": "subgraph_274_FATHER-IN-LAW (OF MAN)",
  "HUSBAND": "subgraph_147_MARRY",
  "WOOL": "subgraph_550_FUR",
  "BITTER": "subgraph_560_SWEET",
  "TIE UP (TETHER)": "subgraph_838_TIE",
  "ARM": "subgraph_377_ARM",
  "HOUR": "subgraph_656_TIME",
  "SIT": "subgraph_104_DWELL (LIVE, RESIDE)",
  "MANNER": "subgraph_743_PATH",
  "EYEBROW": "subgraph_1033_EYEBROW",
  "ACCUSE": "subgraph_519_FAULT",
  "FALL ASLEEP": "subgraph_888_SLEEP",
  "GIRL": "subgraph_341_CHILD (DESCENDANT)",
  "GO OUT": "subgraph_57_RISE (MOVE UPWARDS)",
  "BUY": "subgraph_88_GET",
  "YOU": "subgraph_893_HE",
  "DISH": "subgraph_817_BOWL",
  "MALE (OF PERSON)": "subgraph_339_FATHER",
  "WISE": "subgraph_1091_CLEVER",
  "VIOLENCE": "subgraph_1035_STRENGTH",
  "GARDEN-HOUSE": "subgraph_848_HOUSE",
  "THIEF": "subgraph_852_BURY",
  "TAKE": "subgraph_59_TAKE",
  "FAR": "subgraph_721_HIGH",
  "BEAD": "subgraph_798_SEED",
  "CROOKED": "subgraph_610_TWIST",
  "SHELF": "subgraph_399_TREE",
  "MATCH": "subgraph_664_FIRE",
  "THING": "subgraph_447_FEW",
  "STORM CLOUDS": "subgraph_626_SKY",
  "BOOK": "subgraph_889_LETTER",
  "PLAY": "subgraph_295_RUN",
  "HEALTHY": "subgraph_139_CORRECT (RIGHT)",
  "GRANDDAUGHTER": "subgraph_156_MOTHER-IN-LAW (OF MAN)",
  "TOOL": "subgraph_951_THING",
  "DEAD": "subgraph_460_KILL",
  "COUNT (QUANTITY)": "subgraph_1074_AMOUNT",
  "SUGAR": "subgraph_170_GOOD",
  "WASH": "subgraph_544_FLOW",
  "ACQUIT": "subgraph_833_LET GO OR SET FREE",
  "BOTTOM": "subgraph_9_END (OF SPACE)",
  "MOTOR": "subgraph_1020_CAR",
  "FREEZE": "subgraph_1004_SHAKE",
  "RAPIDS": "subgraph_1078_RAPIDS",
  "PICK UP": "subgraph_44_TAKE",
  "EWE": "subgraph_1014_SHEEP",
  "HONEY": "subgraph_628_SWEET",
  "BEAK": "subgraph_169_END (OF SPACE)",
  "ELECTRICITY": "subgraph_248_FIRE",
  "DAMAGE": "subgraph_595_DESTROY",
  "PREACH": "subgraph_257_SAY",
  "SOUTH": "subgraph_1063_SOUTH",
  "DEBT": "subgraph_724_COUNT",
  "CALCULATE": "subgraph_588_COUNT",
  "PEPPER": "subgraph_1056_PEPPER",
  "FIN": "subgraph_507_FEATHER",
  "DRIVE (CATTLE)": "subgraph_352_LEAVE",
  "DAY (24 HOURS)": "subgraph_392_WORLD",
  "IRON": "subgraph_823_IRON",
  "STRONG": "subgraph_281_BIG",
  "BELOW OR UNDER": "subgraph_414_BOTTOM",
  "GUEST": "subgraph_831_MASTER",
  "SAY": "subgraph_101_SAY",
  "WORK (LABOUR)": "subgraph_468_BUILD",
  "MANY": "subgraph_179_BIG",
  "MOTHER": "subgraph_213_MOTHER-IN-LAW (OF MAN)",
  "LAST (FINAL)": "subgraph_125_END (OF SPACE)",
  "VEGETABLES": "subgraph_594_PLANT (VEGETATION)",
  "FEVER": "subgraph_789_SICK",
  "OLDER SIBLING": "subgraph_576_BROTHER",
  "SHIN": "subgraph_809_LEG",
  "SLAVE": "subgraph_1027_SLAVE",
  "WAKE UP": "subgraph_599_RISE (MOVE UPWARDS)",
  "SOUR": "subgraph_560_SWEET",
  "COTTON": "subgraph_983_ROPE",
  "ROOF": "subgraph_323_TOP",
  "SON-IN-LAW (OF WOMAN)": "subgraph_254_MOTHER-IN-LAW (OF WOMAN)",
  "NOISE": "subgraph_740_VOICE",
  "TRAP (CATCH)": "subgraph_76_GET",
  "OLD MAN": "subgraph_250_MAN",
  "HAND": "subgraph_77_GIVE",
  "WEEK": "subgraph_1065_SUNDAY",
  "STINGY": "subgraph_1062_GREEDY",
  "OBSCURE": "subgraph_882_DARKNESS",
  "REFUSE": "subgraph_769_DEFEND",
  "CASSAVA": "subgraph_1061_MANIOC BREAD",
  "OLDER SISTER": "subgraph_545_COUSIN",
  "SHARE": "subgraph_143_LEAVE",
  "HUNT": "subgraph_109_TAKE",
  "FOWL": "subgraph_841_ANIMAL",
  "WATERFALL": "subgraph_1078_RAPIDS",
  "ANKLE": "subgraph_657_LEG",
  "HOLD": "subgraph_28_TAKE",
  "SAND": "subgraph_27_EARTH (SOIL)",
  "FROST": "subgraph_971_COLD",
  "BUNDLE": "subgraph_706_TIE",
  "FATHER": "subgraph_56_FATHER-IN-LAW (OF MAN)",
  "BURNING": "subgraph_152_COUNT",
  "BRAVE": "subgraph_904_STRONG",
  "MILK": "subgraph_728_HEART",
  "BLOW (OF WIND)": "subgraph_432_BLOW (OF WIND)",
  "DAUGHTER-IN-LAW (OF MAN)": "subgraph_102_MOTHER-IN-LAW (OF WOMAN)",
  "TIP (OF OBJECT)": "subgraph_418_END (OF SPACE)",
  "FORKED BRANCH": "subgraph_765_BRANCH",
  "BOSS": "subgraph_526_HEAD",
  "RECOGNIZE (SOMEBODY)": "subgraph_409_KNOW (SOMETHING)",
  "AREA": "subgraph_228_PLACE (POSITION)",
  "BE ALIVE": "subgraph_78_SPIRIT",
  "SELL": "subgraph_89_GIVE",
  "KICK": "subgraph_517_STRIKE OR BEAT",
  "HITHER (HERE TO)": "subgraph_797_THAT",
  "TWO": "subgraph_720_FEW",
  "SHALLOW": "subgraph_235_LOW",
  "WEIGH": "subgraph_435_COUNT",
  "STUDY": "subgraph_112_KNOW (SOMETHING)",
  "BAD LUCK": "subgraph_541_PAIN",
  "DOWN": "subgraph_374_BOTTOM",
  "SPRING (OF WATER)": "subgraph_1084_SPRING (OF WATER)",
  "ELEVATION": "subgraph_1017_MOUNTAIN",
  "LOOK FOR": "subgraph_151_GET",
  "NAPE (OF NECK)": "subgraph_587_VOICE",
  "WOUND": "subgraph_489_DESTROY",
  "BACK (DIRECTION)": "subgraph_1083_BACK (DIRECTION)",
  "NEAR": "subgraph_583_SIDE",
  "CLOUD": "subgraph_346_SKY",
  "CAN": "subgraph_651_IRON",
  "LAUGHTER": "subgraph_1042_LAUGH",
  "AFTERWARDS": "subgraph_778_LATE",
  "COVER": "subgraph_672_BURY",
  "EYELID": "subgraph_1033_EYEBROW",
  "INCREASE": "subgraph_502_RISE (MOVE UPWARDS)",
  "ICE": "subgraph_1069_ICE",
  "UNCLE": "subgraph_110_FATHER-IN-LAW (OF MAN)",
  "FEAR (FRIGHT)": "subgraph_947_GRIEF",
  "READ": "subgraph_116_UNDERSTAND",
  "HAIR (BODY)": "subgraph_381_FUR",
  "WHEAT": "subgraph_639_GRAIN",
  "CITIZEN": "subgraph_260_RELATIVES",
  "BEER": "subgraph_828_BEVERAGE",
  "CORNER": "subgraph_357_EDGE",
  "EDGE": "subgraph_113_END (OF SPACE)",
  "FORTRESS": "subgraph_696_WALL (OF HOUSE)",
  "TIME": "subgraph_191_PLACE (POSITION)",
  "EAR": "subgraph_624_HEAR",
  "FLOCK (OF ANIMALS)": "subgraph_1081_FLOCK (OF ANIMALS)",
  "DAUGHTER-IN-LAW (OF WOMAN)": "subgraph_254_MOTHER-IN-LAW (OF WOMAN)",
  "GARDEN": "subgraph_709_FIELD",
  "YAM": "subgraph_1031_YAM",
  "PIT (POTHOLE)": "subgraph_970_HOLE",
  "TURN (SOMETHING)": "subgraph_192_TWIST",
  "SISTER": "subgraph_224_COUSIN",
  "MORE": "subgraph_703_MANY",
  "INSIDE": "subgraph_440_BOTTOM",
  "HARE": "subgraph_1049_RABBIT",
  "TRUTH": "subgraph_854_CORRECT (RIGHT)",
  "DAY BEFORE YESTERDAY": "subgraph_1059_DAY BEFORE YESTERDAY",
  "OWN": "subgraph_20_GET",
  "ONE TIME": "subgraph_1088_ONCE (IN THE PAST)",
  "HAY": "subgraph_719_PLANT (VEGETATION)",
  "LEAD (GUIDE)": "subgraph_100_LEAVE",
  "WAIST": "subgraph_662_BACK",
  "MEMORY": "subgraph_523_SPIRIT",
  "HIT": "subgraph_538_KILL",
  "FLY (MOVE THROUGH AIR)": "subgraph_770_BLOW (OF WIND)",
  "DAY AFTER TOMORROW": "subgraph_1059_DAY BEFORE YESTERDAY",
  "TORTOISE": "subgraph_1093_TURTLE",
  "SHIELD": "subgraph_1064_ARMOUR",
  "EMERGE (APPEAR)": "subgraph_883_SHOW",
  "TASTY": "subgraph_808_SWEET",
  "TABLE": "subgraph_399_TREE",
  "FRAGRANT": "subgraph_629_SMELL (STINK)",
  "GIVE BACK": "subgraph_673_COME BACK",
  "BLANKET": "subgraph_985_BLANKET",
  "BLUNT": "subgraph_1051_BLIND",
  "QUIET": "subgraph_785_QUIET",
  "MOLD": "subgraph_214_BUILD",
  "RING": "subgraph_630_FOOT",
  "BECAUSE": "subgraph_989_WHEN",
  "PAPER": "subgraph_354_KILL",
  "GUILTY": "subgraph_950_FAULT",
  "CAUSE": "subgraph_533_DO OR MAKE",
  "RAFTER": "subgraph_830_POST",
  "COUNTRY": "subgraph_55_PLACE (POSITION)",
  "WRAP": "subgraph_289_TWIST",
  "CONDEMN": "subgraph_497_FAULT",
  "THROAT": "subgraph_685_VOICE",
  "TEACHER": "subgraph_1087_PUPIL (STUDENT)",
  "DOORPOST": "subgraph_781_POST",
  "SOLID": "subgraph_474_BIG",
  "PINE": "subgraph_1068_PINE",
  "STONE OR ROCK": "subgraph_998_PRECIPICE",
  "EYE": "subgraph_438_GRAIN",
  "JOG (SOMETHING)": "subgraph_978_SHAKE",
  "COUSIN": "subgraph_144_COUSIN",
  "SHOP": "subgraph_422_BUILD",
  "BIG": "subgraph_46_BIG",
  "MARRY": "subgraph_12_TAKE",
  "COMMON COLD (DISEASE)": "subgraph_846_COLD",
  "PATH": "subgraph_718_PATH",
  "SIT DOWN": "subgraph_766_SIT",
  "MUTE": "subgraph_1025_MUTE",
  "PICK": "subgraph_395_TEAR (SHRED)",
  "HE": "subgraph_859_THAT",
  "THIRST": "subgraph_1040_HUNGER",
  "HAVE SEX": "subgraph_732_SLEEP",
  "MORNING": "subgraph_653_EARLY",
  "RING (MAKE SOUND)": "subgraph_917_CHIME (ACTION)",
  "REMEMBER": "subgraph_218_THINK (BELIEVE)",
  "FLEE": "subgraph_268_LEAVE",
  "ESCAPE": "subgraph_821_FLEE",
  "RAFT": "subgraph_1021_BOAT",
  "BEND (SOMETHING)": "subgraph_948_FOLD",
  "SAUCER": "subgraph_817_BOWL",
  "TRY": "subgraph_462_HEAR",
  "COMB": "subgraph_1046_BRUSH",
  "CUT DOWN": "subgraph_358_CHOP",
  "DROWN": "subgraph_394_FALL",
  "IMITATE": "subgraph_619_FEEL",
  "HIGH": "subgraph_66_TOP",
  "ROOT": "subgraph_411_BOTTOM",
  "CALM": "subgraph_975_QUIET",
  "LAY (VERB)": "subgraph_256_GIVE",
  "PETROLEUM": "subgraph_581_MEDICINE",
  "PLAIN": "subgraph_383_FLAT",
  "BELLY": "subgraph_361_SPIRIT",
  "SUCK": "subgraph_197_DRINK",
  "STILL (CONTINUING)": "subgraph_299_YOUNG",
  "HOUSE": "subgraph_243_HOUSE",
  "DRIVE": "subgraph_92_LEAVE",
  "BREAK (CLEAVE)": "subgraph_301_BREAK (DESTROY OR GET DESTROYED)",
  "BUSINESS": "subgraph_638_BUILD",
  "MOTHER-IN-LAW (OF MAN)": "subgraph_150_FATHER-IN-LAW (OF MAN)",
  "BEGET": "subgraph_269_DO OR MAKE",
  "FLOOR": "subgraph_32_EARTH (SOIL)",
  "THROW": "subgraph_93_LEAVE",
  "CAVE": "subgraph_970_HOLE",
  "WATER": "subgraph_244_RIVER",
  "SIDE": "subgraph_199_EDGE",
  "BRUSH": "subgraph_1046_BRUSH",
  "DARK": "subgraph_458_DIRTY",
  "TRADE OR BARTER": "subgraph_559_BUY",
  "CURASSOW": "subgraph_1050_CURASSOW",
  "MIND": "subgraph_108_SPIRIT",
  "LOAD": "subgraph_887_HEAVY",
  "HEEL": "subgraph_657_LEG",
  "SPEECH": "subgraph_122_SAY",
  "CRIME": "subgraph_950_FAULT",
  "DEEP": "subgraph_233_LOW",
  "FEMALE (OF PERSON)": "subgraph_865_WOMAN",
  "BREATH": "subgraph_363_SPIRIT",
  "CARRY": "subgraph_74_TAKE",
  "RELATIVES": "subgraph_45_BROTHER",
  "SUMMER": "subgraph_911_YEAR",
  "EMPTY": "subgraph_802_QUIET",
  "TRUE": "subgraph_478_CORRECT (RIGHT)",
  "YOUNGER SIBLING": "subgraph_623_BROTHER",
  "SHRIEK": "subgraph_788_SING",
  "NARROW": "subgraph_294_SMALL",
  "BRASS INSTRUMENT (HORN OR TRUMPET)": "subgraph_924_BRANCH",
  "CLOAK": "subgraph_775_CLOTHES",
  "WIFE": "subgraph_492_WOMAN",
  "WEIGHT": "subgraph_614_WEIGH",
  "SLEEP (STATE)": "subgraph_888_SLEEP",
  "FLOAT": "subgraph_649_FLOW",
  "OVEN": "subgraph_574_COOK (SOMETHING)",
  "AT THAT TIME": "subgraph_778_LATE",
  "AT": "subgraph_914_INSIDE",
  "ALWAYS": "subgraph_906_MANY",
  "TIDE": "subgraph_1060_HIGH TIDE",
  "SEED": "subgraph_351_GRAIN",
  "FATHER'S BROTHER": "subgraph_429_AUNT",
  "COLD (OF WEATHER)": "subgraph_829_COLD",
  "SPRING OR WELL": "subgraph_650_DRINK",
  "RIPE": "subgraph_419_YELLOW",
  "BABY": "subgraph_282_CHILD (DESCENDANT)",
  "SNAIL": "subgraph_991_SHELL",
  "INJURE": "subgraph_446_DESTROY",
  "RUB": "subgraph_597_SCRAPE",
  "LONG": "subgraph_178_BIG",
  "CONVEY (A MESSAGE)": "subgraph_369_SAY",
  "STINKING": "subgraph_761_SMELL (STINK)",
  "JAW": "subgraph_921_FACE",
  "BLAME": "subgraph_713_FAULT",
  "BETWEEN": "subgraph_540_PLACE (POSITION)",
  "VULVA": "subgraph_1089_VAGINA",
  "SNAKE": "subgraph_932_ANIMAL",
  "DISTANCE": "subgraph_292_PLACE (POSITION)",
  "WRIST": "subgraph_632_ARM",
  "GUESS": "subgraph_198_KNOW (SOMETHING)",
  "TIE": "subgraph_324_TWIST",
  "PONCHO": "subgraph_757_COAT",
  "CARCASS": "subgraph_51_SPIRIT",
  "HEAVEN": "subgraph_622_SKY",
  "MORTAR CRUSHER": "subgraph_990_GRIND",
  "FISH POISON": "subgraph_870_CURE",
  "PULL": "subgraph_117_LEAD (GUIDE)",
  "NOSTRIL": "subgraph_607_BEAK",
  "GUAN": "subgraph_1050_CURASSOW",
  "SHOE": "subgraph_1039_SHOE",
  "NIPPLE": "subgraph_728_HEART",
  "PAN": "subgraph_817_BOWL",
  "FRUIT": "subgraph_554_GRAIN",
  "HEIGHT": "subgraph_1015_MOUNTAIN",
  "BAD": "subgraph_448_DIRTY",
  "RAG": "subgraph_872_CLOTHES",
  "ORDER": "subgraph_137_SAY",
  "STEPMOTHER": "subgraph_485_MOTHER-IN-LAW (OF WOMAN)",
  "HEAD LOUSE": "subgraph_1070_HEAD LOUSE",
  "WHY": "subgraph_825_WHAT",
  "FLAT": "subgraph_47_EARTH (SOIL)",
  "FAT (OBESE)": "subgraph_427_MEDICINE",
  "FATHER-IN-LAW (OF WOMAN)": "subgraph_4_FATHER-IN-LAW (OF MAN)",
  "STRANGER": "subgraph_710_MASTER",
  "HAVE": "subgraph_63_GET",
  "HERD (SOMETHING)": "subgraph_984_PRESERVE",
  "PRAISE": "subgraph_670_ASK (REQUEST)",
  "PIN": "subgraph_1019_NEEDLE (FOR SEWING)",
  "NEST": "subgraph_895_LAIR",
  "IN FRONT OF": "subgraph_779_FACE",
  "CALL BY NAME": "subgraph_16_SAY",
  "CHEEK": "subgraph_1012_FACE",
  "SUCCEED": "subgraph_210_COME",
  "FEEL (TACTUALLY)": "subgraph_556_HEAR",
  "NO": "subgraph_905_FORBID",
  "FORK": "subgraph_944_HOOK",
  "LAGOON": "subgraph_763_LAKE",
  "GOLD": "subgraph_776_YELLOW",
  "PREPARE": "subgraph_792_COOK (SOMETHING)",
  "FIG": "subgraph_1073_BANYAN",
  "OMEN": "subgraph_926_GRIEF",
  "RIVER": "subgraph_307_RIVER",
  "BE ABLE": "subgraph_409_KNOW (SOMETHING)",
  "ASK (REQUEST)": "subgraph_40_ASK (REQUEST)",
  "BOIL (OF SKIN)": "subgraph_897_WOUND",
  "SEIZE": "subgraph_164_TAKE",
  "SILVER": "subgraph_972_IRON",
  "PILL": "subgraph_674_RESCUE",
  "OX": "subgraph_683_ANIMAL",
  "PEN": "subgraph_803_FEATHER",
  "BRUISE": "subgraph_897_WOUND",
  "PRECIPICE": "subgraph_404_EDGE",
  "PLOUGH": "subgraph_1010_PLANT (SOMETHING)",
  "CHARCOAL": "subgraph_516_FIRE",
  "RAT": "subgraph_1054_RAT",
  "SHEEP": "subgraph_1014_SHEEP",
  "ROUGH (OF SEA)": "subgraph_1076_WAVE",
  "TUMBLE (FALL DOWN)": "subgraph_832_SINK (DESCEND)",
  "POTATO": "subgraph_1031_YAM",
  "SMOOTH": "subgraph_264_THIN (OF SHAPE OF OBJECT)",
  "NETBAG": "subgraph_993_TRAP (PITFALL)",
  "SWAY": "subgraph_976_MOVE (ONESELF)",
  "LEG": "subgraph_259_LEG",
  "CORN FIELD": "subgraph_53_EARTH (SOIL)",
  "HARVEST": "subgraph_639_GRAIN",
  "MULE": "subgraph_1016_HORSE",
  "AGAIN": "subgraph_473_YOUNG",
  "MOUSE": "subgraph_1054_RAT",
  "SLEEP": "subgraph_428_SLEEP",
  "AT FIRST": "subgraph_840_EARLY",
  "WOOD": "subgraph_120_TREE",
  "THREAD": "subgraph_912_LINE",
  "TOP": "subgraph_86_TOP",
  "SUN": "subgraph_271_LIGHT (RADIATION)",
  "FOREST": "subgraph_716_TREE",
  "PLAIT OR BRAID OR WEAVE": "subgraph_154_TWIST",
  "STEPFATHER": "subgraph_368_FATHER-IN-LAW (OF MAN)",
  "AGE": "subgraph_659_TIME",
  "TENDON": "subgraph_302_BOTTOM",
  "GOAT": "subgraph_1014_SHEEP",
  "DIRTY": "subgraph_30_EARTH (SOIL)",
  "KILL": "subgraph_62_KILL",
  "TONE (MUSIC)": "subgraph_740_VOICE",
  "BALL": "subgraph_558_FOOT",
  "IDOL": "subgraph_1071_IDOL",
  "SHOULDERBLADE": "subgraph_1057_SHOULDERBLADE",
  "OIL (ORGANIC SUBSTANCE)": "subgraph_816_FAT (ORGANIC SUBSTANCE)",
  "MOUNTAIN": "subgraph_1017_MOUNTAIN",
  "SUMMIT": "subgraph_861_HEAD",
  "GRASP": "subgraph_118_GET",
  "MAD": "subgraph_1025_MUTE",
  "HE-GOAT": "subgraph_1014_SHEEP",
  "BRACKISH": "subgraph_524_SWEET",
  "BOY": "subgraph_236_CHILD (DESCENDANT)",
  "SPEAR": "subgraph_477_IRON",
  "SOFT": "subgraph_403_YOUNG",
  "MEN'S HOUSE": "subgraph_848_HOUSE",
  "COLLAR": "subgraph_999_NECK",
  "ADZE": "subgraph_1037_BATTLE-AXE",
  "BEHIND": "subgraph_183_LATE",
  "CHEST": "subgraph_455_SPIRIT",
  "PROTECT": "subgraph_434_KEEP",
  "BEGGAR": "subgraph_1038_POOR",
  "NOSE": "subgraph_795_BEAK",
  "WE (INCLUSIVE)": "subgraph_1022_WE (EXCLUSIVE)",
  "DESTROY": "subgraph_333_DESTROY",
  "DITCH": "subgraph_898_HOLE",
  "HUNGER": "subgraph_1040_HUNGER",
  "TELL": "subgraph_123_SAY",
  "WINE": "subgraph_828_BEVERAGE",
  "THAT": "subgraph_863_THAT",
  "HAWK": "subgraph_1041_VULTURE",
  "MOVE": "subgraph_196_LEAVE",
  "PUPIL (STUDENT)": "subgraph_1087_PUPIL (STUDENT)",
  "GRASS-SKIRT": "subgraph_936_CLOTHES",
  "STONE": "subgraph_1017_MOUNTAIN",
  "FIR": "subgraph_1068_PINE",
  "YOUNG": "subgraph_81_CHILD (DESCENDANT)",
  "RIPEN": "subgraph_276_YELLOW",
  "CARRY ON HEAD": "subgraph_335_CARRY",
  "WRONG": "subgraph_652_BAD",
  "BRANCH": "subgraph_255_ARM",
  "FISHNET": "subgraph_844_TRAP (PITFALL)",
  "ONE": "subgraph_542_FEW",
  "VINE": "subgraph_874_THREAD",
  "RULE": "subgraph_133_LEAVE",
  "SERVANT": "subgraph_918_FENCE",
  "EAGLE": "subgraph_1041_VULTURE",
  "EYELASH": "subgraph_1033_EYEBROW",
  "TREE": "subgraph_120_TREE",
  "UNDERSTAND": "subgraph_25_UNDERSTAND",
  "FAST": "subgraph_707_EARLY",
  "SKY": "subgraph_17_TOP",
  "FOOTPRINT": "subgraph_296_LEG",
  "KNOCK": "subgraph_663_KILL",
  "BLACK": "subgraph_356_DIRTY",
  "PARENTS": "subgraph_442_RELATIVES",
  "BEAM": "subgraph_552_POST",
  "BECOME SICK": "subgraph_940_SICK",
  "LISTEN": "subgraph_316_HEAR",
  "SANDFLY": "subgraph_1032_MOSQUITO",
  "NUT": "subgraph_604_GRAIN",
  "TODAY": "subgraph_965_IMMEDIATELY",
  "NECK": "subgraph_587_VOICE",
  "MOORLAND": "subgraph_908_CLAY",
  "MIRROR": "subgraph_939_DOOR",
  "SWEET": "subgraph_353_GOOD",
  "LATCH": "subgraph_1023_LATCH",
  "ALCOHOL (FERMENTED DRINK)": "subgraph_828_BEVERAGE",
  "SPRINGTIME": "subgraph_780_YEAR",
  "JUDGMENT": "subgraph_796_BLAME",
  "FAN ACTION": "subgraph_678_BLOW (OF WIND)",
  "LOWER LEG": "subgraph_814_LEG",
  "RUDDER": "subgraph_1008_MIX",
  "HAPPINESS": "subgraph_1075_JOY",
  "WE (EXCLUSIVE)": "subgraph_1022_WE (EXCLUSIVE)",
  "INSECT": "subgraph_962_ANIMAL",
  "PRISON": "subgraph_1027_SLAVE",
  "WINTER": "subgraph_655_COLD",
  "FISHING LINE": "subgraph_980_LINE",
  "RIDE": "subgraph_21_RISE (MOVE UPWARDS)",
  "DUCK": "subgraph_1080_GOOSE",
  "MOVE (ONESELF)": "subgraph_240_LEAVE",
  "FOREIGN": "subgraph_1067_OTHER",
  "INJECTION": "subgraph_758_NAIL (TOOL)",
  "PHYSICIAN": "subgraph_1034_MAGICIAN",
  "WHO": "subgraph_935_WHAT",
  "OUTSIDE": "subgraph_616_BEHIND",
  "DIRT": "subgraph_699_DIRTY",
  "FOLD": "subgraph_239_TWIST",
  "LIP": "subgraph_287_EDGE",
  "BOOT": "subgraph_1039_SHOE",
  "STUPID": "subgraph_1025_MUTE",
  "WIDOW": "subgraph_1079_WIDOW",
  "MANIOC BREAD": "subgraph_1061_MANIOC BREAD",
  "AWL": "subgraph_1019_NEEDLE (FOR SEWING)",
  "DEFEND": "subgraph_362_KEEP",
  "DRESS UP": "subgraph_97_PUT",
  "FEMALE": "subgraph_573_WOMAN",
  "MOVE (AFFECT EMOTIONALLY)": "subgraph_660_CATCH",
  "CIRCLE": "subgraph_749_FOOT",
  "DARKNESS": "subgraph_711_DARKNESS",
  "GO DOWN (DESCEND)": "subgraph_425_ARRIVE",
  "SPIN": "subgraph_207_TWIST",
  "MALE (OF ANIMAL)": "subgraph_667_MAN",
  "MONTH": "subgraph_927_SUN",
  "SUDDENLY": "subgraph_819_IMMEDIATELY",
  "SPREAD OUT": "subgraph_443_PULL",
  "FIGHT": "subgraph_366_KILL",
  "URGE (SOMEONE)": "subgraph_675_DRIVE",
  "HOWL": "subgraph_788_SING",
  "DRINK": "subgraph_161_RIVER",
  "HIRE": "subgraph_327_GET",
  "BULL": "subgraph_683_ANIMAL",
  "SEAT (SOMEBODY)": "subgraph_256_GIVE",
  "BURY": "subgraph_518_BURY",
  "DEFEAT": "subgraph_1048_VICTORY",
  "GOOSE": "subgraph_1080_GOOSE",
  "STORY": "subgraph_1026_STORY",
  "ABOVE": "subgraph_426_TOP",
  "SOUP": "subgraph_661_DRINK",
  "DRIP (FALL IN GLOBULES)": "subgraph_211_LET GO OR SET FREE",
  "LEAD (CHEMICAL ELEMENT)": "subgraph_961_IRON",
  "FAN (OBJECT)": "subgraph_952_BLOW (OF WIND)",
  "FINGERNAIL": "subgraph_879_CLAW",
  "FORGIVE": "subgraph_310_LET GO OR SET FREE",
  "KNEAD": "subgraph_338_KNEAD",
  "SHOUT": "subgraph_596_CALL",
  "SHADE": "subgraph_476_SPIRIT",
  "OLDER BROTHER": "subgraph_545_COUSIN",
  "SALT": "subgraph_857_SALTY",
  "TWIST": "subgraph_64_TWIST",
  "RAIN (RAINING)": "subgraph_981_YEAR",
  "SWALLOW": "subgraph_459_DRINK",
  "DIFFICULT": "subgraph_512_STRONG",
  "ITEM": "subgraph_1009_THING",
  "TAIL": "subgraph_922_BUTTOCKS",
  "KNEE": "subgraph_745_ARM",
  "SUSPECT": "subgraph_359_KNOW (SOMETHING)"
};